### ISSUE TITLE
Proposal to change factory definition

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#101]
The factory definition syntax right now uses the same function name, but pattern matches on the first argument. This works ok, but it does cause a few problems

* You can't easily use ctags/symbol view to jump to factories because they are all the same function
* You can't add functions that are used by an factory in between other factories since they are all the same function and elixir will raise a warning.

I propose that we change the factory definition syntax to {factory_name}_factory. This will also make it so we can add callbacks that are grouped near the factory in the future

```elixir
defmodule Factory do
  # This is nice because you can add functions for the user factory near it instead of at the bottom
  # Also works better with symbol view so it doesn't show a bunch of `factory` functions.
  def user_factory do
    %User{
      first_name: "Paul",
      last_name: "Smith",
    }
  end
  
  # You can now define helper functions near the factory that it applies to
  def make_admin(user) do
    assing_to_admin_group(user)
  end
  
  # In the future we could add callbacks like this. If we keep the current syntax you'd have to put these
  # at the bottom of the file which makes it hard to see what a factory can do
  def after_build_user(user, attrs) do
    email = attrs.first_name <> attrs.last_name <> "@foo.com"
    Map.put_new(user, :email, email)
  end
  
  def comment_factory do
    %Comment{
      body: "This is my comment"
    }
  end
end
```

You would still call these with the same function `build(:user)`, etc.

**Comment by drapergeek** [comment]
This makes sense to me, I think it's a good change early in the life of the tool.

**Comment by lpil** [comment]
Commenting here so I am notified when/if this change makes it into master so I can possibly do work for #97

**Comment by derekprior** [comment]
This makes `create(:user)` just a tad more magical to me. Not enough to turn me off completely, but worth noting, perhaps.

I agree that the helper functions/traits/callbacks at the bottom of the factory file are really difficult to keep track of. I often have no idea which helpers/traits are intended to work with which factories.

Sometimes, though, the helpers are generic enough that they can work for multiple factories. In which case, the inline ordering also breaks down.

I guess I'm saying I'm not really sure right now if I'd like this or not.

**Comment by paulcsmith** [comment]
I assume that if a function works for multiple factories it would go at the bottom and if it's for a specific factory it would go near that factory, but that is still a valid point. It's one more thing to think about.

That's also a good point about `create(:user)` being more magical...Another option would be to make the factory definition a macro like we had before and automatically generated build/create/etc. functions

```elixir
# Defines `build_user`, `create_user`, `create_user_pair`, `create_user_list`
factory :user do
  %User{name: "John"}
end
```

Another option would be to encourage people to put functions that apply to specific factories in their own modules? 

```elixir
# Import this in your tests or create a __using__ in your factory that imports all traits
defmodule UserTraits do
  def make_admin(user) do
    assign_to_admin_group
  end
end
```

**Comment by lpil** [comment]
I think I prefer the use of macros.

I'm not sure I understand your module example.

**Comment by paulcsmith** [comment]
@lpil I updated the example to hopefully clarify what I meant. I was trying to show that you could have a separate module for all the functions that you use to manipulate factories and then import them.

I'm not totally sold on the macro because then you can't jump to the factory with ctags/symbol view. I'm also not totally sure that calling `user_factory` with `build(:user)` will be a big deal either, so a macro just to generate `build_user`, `create_user`, etc. might be overkill. What do you think?
