### ISSUE TITLE
Factories not being wrapped in changesets?

### ISSUE THREAD

**Issue by cdale77** [thoughtbot/ex_machina#103]
Thanks so much for making this! I'm very new to Elixir and Phoenix, so I might be wrong. But I discovered something today that makes me think that factories made with the `create` function are not being wrapped in changesets before hitting the db. 

I have a User model with the following changeset definition. The model also has a `null: false` constraint on `encrypted password`
```
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> validate_length(:email, min: 1)
    |> validate_length(:password, min: 1)
    |> validate_confirmation(:password, message: "Password does not match")
    |> unique_constraint(:email, message: "Email has already been taken")
    |> generate_encrypted_password
  end

  defp generate_encrypted_password(changeset) do
    pass = changeset.params["password"]
    put_change(changeset, :encrypted_password, Comeonin.Bcrypt.hashpwsalt(pass))
  end
```

The User factory:
```
  def factory(:user) do
    %User{email: "example@example.com", password: "password",
          password_confirmation: "password"}
  end
```

And a test to test for unique emails:
```
  test "unique emails" do
    user = create(:user)
    changeset = User.changeset(user, %{email: user.email, password: "password",
                                     password_confirmation: "password"})
    refute changeset.valid?
  end
```

When I run this test, I get a `not_null_violation` as the encrypted password field is blank. Dropping `IEx.pry` into my changeset function indicates the changeset function (and `generate_encrypted_password`) are not being called by Ex Machina. I tried this for other models in my app with the same result. 

When I make a record normally, by creating a changeset then calling `Repo.insert` things work fine. 

The source for `ExMachina.Ecto.save_record` doesn't appear to use a changeset, though I might be misreading this
https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina/ecto.ex#L93

**Comment by cdale77** [comment]
I found a mistake in my test code and updated it, and also re-ran the IEx.pry experiment, and I still could not get pry to fire when placed in the changeset function and running the above test.

**Comment by paulcsmith** [comment]
First off, thanks for leaving such a detailed issue. That makes it much easier to answer your question. 

ExMachina wraps the record in a changeset before inserting, but it's not the user defined changeset. That is why the pry statement is never called.

In ExMachina 1.0.0 it will not be wrapped in a changeset at all.

There is a closed issue on this repo that  has some ideas for handling passwords: https://github.com/thoughtbot/ex_machina/issues/82

Let me know if you have any other questions!
