### ISSUE TITLE
Raise helpful error when using ExMachina.create functions

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#106]
I think it would be good to add helpful errors when calling create, create_pair and create_list on ExMachina so people know that things have changed when they upgrade to 1.0.0

**Comment by paulcsmith** [comment]
@davidkuhta is working on this one I believe :)

**Comment by davidkuhta** [comment]
@paulcsmith 
Note: this is the error-helpers branch.

For create functions with error-helpers: 
https://github.com/davidkuhta/ex_machina/blob/error-helpers/lib/ex_machina.ex#L53

For relevant tests:
https://github.com/davidkuhta/ex_machina/blob/error-helpers/test/ex_machina_test.exs#L102
https://github.com/davidkuhta/ex_machina/blob/error-helpers/test/ex_machina/ecto_strategy_test.exs#L83

**Comment by paulcsmith** [comment]
@davidkuhta This is great. Thanks for working on them. Could you open a pull request for these two issues? That would make it easier to see what changes and give comments :D
