### ISSUE TITLE
remove nil values from params

### ISSUE THREAD

**Issue by gagalago** [thoughtbot/ex_machina#112]
If we don't specify some fields, these fields are nil value on the map returned by `params_for/2`.
Most of the time we don't want to put nil into database. So wy not just remove them ?
```
params
  |> Enum.filter(fn {_, v} -> v != nil end)
  |> Enum.into(%{})
```

**Comment by paulcsmith** [comment]
Hi @gagalago. I don't see a clear reason to go with one or the other. I can see circumstances in which you want to keep the nils and in which you wouldn't so I think it's best to keep them, and let people write their own function that overrides params_for or calls_params for and filters nil.

However, if you have a good use case for why it would always be best to remove nils I would love to discuss this further!
