### ISSUE TITLE
Cast all values before inserting

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#117]
I think this could be very useful for working with times or custom types

**Comment by davidkuhta** [comment]
I'll take a run at this one!

**Comment by jsteiner** [comment]
Whoops! Closed this accidentally.

[I took a stab at an implementation](https://github.com/thoughtbot/ex_machina/compare/js-cast). It's been a while @davidkuhta, so I hope you don't mind. I'm going to test it on a project or two tomorrow before submitting a PR.

**Comment by teamon** [comment]
Hey @jsteiner, what's the status of this one?

**Comment by jsteiner** [comment]
@teamon sorry, forgot to update here. This was merged into master as https://github.com/thoughtbot/ex_machina/commit/d7142b69be2d77d46cda1b06e0ac2ed0d3386046

It's still not up on hex.pm. We'll probably release a new version sometime soon.
