### ISSUE TITLE
Lazy attributes?

### ISSUE THREAD

**Issue by moklett** [thoughtbot/ex_machina#130]
What do y'all think about adding support for "lazy" attributes using functions?

I've got an implementation ready to go.  This commit explains everything and includes some examples that should justify why I think this is useful:

https://github.com/moklett/ex_machina/commit/2bc2fe7e983985a31aa424d753d965682f42dbdc

Here's a little example:

``` elixir
def hero_factory do
  %{
    creature: "Bat",
    nickname: &"#{&1.creature}man",
    vehicle: &"#{&1.creature}mobile"
  }
end

build(:hero)
# => %{creature: "Bat", nickname: "Batman", vehicle: "Batmobile"}

build(:hero, creature: "Spider", vehicle: "webs")
# => %{creature: "Spider", nickname: "Spiderman", vehicle: "webs"}
```

Should I open a pull request?

Thanks!

**Comment by jsteiner** [comment]
This looks awesome @moklett! I'd love to see a PR for this.

**Comment by moklett** [comment]
@jsteiner here you go! https://github.com/thoughtbot/ex_machina/pull/131

**Comment by paulcsmith** [comment]
As discussed in [this comment](https://github.com/thoughtbot/ex_machina/pull/131#issuecomment-282318973) we're going to hold off. The feature seems like a good idea, but Josh and I are not quite ready to support it. We think it'd be great to have as an external lib and we would be happy to link to it in the README if @moklett or someone else wants to tackle it
