### ISSUE TITLE
Create a file for each factory.

### ISSUE THREAD

**Issue by asiniy** [thoughtbot/ex_machina#135]
When app is growing and models amount is growing too, it's simpler just to have a bunch of files, one for each model, like rails `factory_girl` gem does.

But it looks like this gem doesn't either ability to create factories in separate files and documentation. WDYT?

**Comment by philipgiuliani** [comment]
I also already wondered if there is a way to do this. Especially useful when using the [Flexible Factory](https://github.com/thoughtbot/ex_machina#flexible-factories-with-pipes) stuff.

> But it looks like **this gem** doesn't either...

**Comment by paulcsmith** [comment]
By default we use a single factory file for all factory in `factory_girl`, but I see your point. 

If you want different modules/files per factory then I would create them in `test/support/#{factory_name}_factory.ex` then import/alias those in your ConnCase/ModelCase or on a per test basis. Does that answer your question?

There are some thoughts on this here: https://github.com/thoughtbot/ex_machina#where-to-put-your-factories but maybe it could be improved. Any ideas?

**Comment by paulcsmith** [comment]
@philipgiuliani Also, the flexible factory stuff is *much* easier in ExMachina 1.0 beta (on master) because you can put the functions right below the factory that needs them

```elixir
def user_factory do
  %User{}
end

def make_admin(user) do
  %{user | admin: true}
end
```

**Comment by philipgiuliani** [comment]
Oh thanks, yes im using 1.0-beta and i really like it. Actually i haven't thought about splitting them up and importing them into the `App.Factory` module.

This could be a good Solution to split it up. Maybe we could add this "idea" to the README.

```elixir
defmodule MyApp.Factory do
  use ExMachina.Ecto, repo: MyApp.Repo

  import MyApp.Factory.User
  import MyApp.Factory.Article
  ...
end

defmodule MyApp.Factory.User do
  def user_factory do
    %User{}
  end

  def make_admin(user) do
    %{user | admin: true}
  end
end

**Comment by paulcsmith** [comment]
That won't work since the import will only be availably inside of factory, but you could do 

```elixir
defmodule MyApp.Factory do
  use ExMachina.Ecto, repo: MyApp.Repo

  # Call `use MyApp.Factory`
  defmacro __using__(_opts) do
    quote do
      import MyApp.Factory.User
      import MyApp.Factory.Article
    end
  end
  ...
end

defmodule MyApp.Factory.User do
  def user_factory do
    %User{}
  end

  def make_admin(user) do
    %{user | admin: true}
  end
end
```

I will consider adding to the README. I'll have to try it out and hear what people think first. I'd rather not suggest something on the README before knowing it's a good idea :P

**Comment by philipgiuliani** [comment]
Oh exactly, thanks. My project is not big enough yet to use it.. Maybe @asiniy can try it and give feedback!
