### ISSUE TITLE
Association being inserted again by create()

### ISSUE THREAD

**Issue by mikegillis677** [thoughtbot/ex_machina#136]
I'm trying to use ExMachina alongside Ecto to test some code with some models with lots of relations, but I keep running into an error where create() tries to insert a relation a second time.

Here's what my test code looks like so far:
```
def factory(:contact) do
  %Contact{
  }
end

def factory(:contact_profile) do
  %ContactProfile{
    city: "Plano",
    region: "TX",
  }
end

contact_profile = create(:contact_profile)
contact = create(:contact, contact_profile: contact_profile)
```

After the last line, I keep getting this error:
```
     ** (Ecto.ConstraintError) constraint error when attempting to insert model:
     
         * unique: contact_profiles_pkey
```

As far as the model goes, the ContactProfile model has a belongs_to relationship with Contact, and Contact has a has_one relationship with ContactProfile.

**Comment by paulcsmith** [comment]
Is the contact factory just returning an empty struct or did you remove things from it for the issue? Also, the currently released version of ExMachina has a lot of custom code to save associations since Ecto 1.x did not handle those automatically. Ecto 2.0 and ExMachina 1.0.0 work together nicely and should handle associations better. I would recommend trying those out. As soon as Ecto 2.0 is out of beta, we will also launch ExMachina 1.0 which should fix a lot of these issues

**Comment by mikegillis677** [comment]
Thanks for the heads up regarding Ecto 2.0!

The Contact factory is currently returning an empty struct, since the Contact model is mostly a container to relate several other Models together.  I had another version of my code where the Contact factory called build(:contact_profile), but that didn't work right either.

**Comment by paulcsmith** [comment]
@mikegillis677 Hmm this does seem odd. I've seen this before, but I am not entirely sure that it is ExMachina. Can you try dropping your test db and running the test again? Also could you try `create(:contact_profile)` by itself and see what happens? Could you also provide the models that are being called. Maybe something in the schema will provide a clue :)

**Comment by mikegillis677** [comment]
`create(:contact_profile)` by itself doesn't error.

Here's my models:
```
defmodule Project.Contact do
  use Project.Web, :model

  schema "contacts" do
    belongs_to :person, Project.Person
    has_one :contact_profile, Project.ContactProfile
    has_many :conversation_participants, through: [:person, :conversation_participant]
    has_many :channel_identifiers, Project.ChannelIdentifier
    has_many :contact_discipleship_lessons, Project.ContactDiscipleshipLesson
    has_many :discipleship_lessons, through: [:contact_discipleship_lessons, :discipleship_lesson]

    timestamps
  end

  @required_fields ~w()
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

defmodule Project.ContactProfile do
  use Project.Web, :model

  schema "contact_profiles" do
    field :first_name, :string
    field :last_name, :string
    field :city, :string
    field :region, :string
    field :postal, :string
    field :latitude, :decimal
    field :longitude, :decimal
    field :gospel_topic, :string
    field :device, :string
    field :visitor_id, :string
    belongs_to :contact, Project.Contact
    belongs_to :country, Project.Country
    belongs_to :language, Project.Language
    belongs_to :gospel_language, Project.GospelLanguage
    belongs_to :faith_response, Project.FaithResponse
    belongs_to :primary_channel, Project.PrimaryChannel
    belongs_to :primary_channel_identifier, Project.PrimaryChannelIdentifier

    timestamps
  end

  @required_fields ~w(first_name last_name city region postal latitude longitude gospel_topic device visitor_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

**Comment by dineshba** [comment]
I have a similar problem.
```def factory(:role) do
    %Role{
      name: "Developer"
    }
  end
  
  def factory(:slot) do
      %Slot{
        role_id: create(:role).id,
      }
  end```
and ```create(:role, role_id: create(:role_id)```
creates two role which i don't want. Is this a bug or am i doing anything wrongly ??

**Comment by paulcsmith** [comment]
@dineshba In this case that is mistake in the code. When creating associations you should set the association, not the association's id. Also you should only call `build` inside the factory otherwise there will indeed two records created. So what it should look like is:

```elixir
def factory(:role) do
  %Role{
    name: "Developer"
  }
end

def factory(:slot) do
  %Slot{
    role: build(:role)
  }
end
```

If you have the appropriate relations set up in your models (has_many, belongs_to, has_one, etc.) then ExMachina will know how to insert the association when you call `create(:role, role: create(:role, name: "Whatever"))
