### ISSUE TITLE
Multiple Factory Files

### ISSUE THREAD

**Issue by maxsalven** [thoughtbot/ex_machina#154]
When I split my factory into two separate files, I get import conflicts:
`imported Myapp.UserFactory.build/1 conflicts with local function`

```elixir
defmodule Myapp.UserFactory do
  use ExMachina.Ecto, repo: Myapp.Repo

  def user_factory do
    %Myapp.User{
      name: "John"
    }
  end
end

defmodule Myapp.ArticleFactory do
  use ExMachina.Ecto, repo: Myapp.Repo
  import Myapp.UserFactory

  def article_factory do
    %Myapp.Article{
      title: "Hello",
      user: build(:user)
    }
  end
end
```

**Comment by pdawczak** [comment]
Hi @maxsalven,

I'm afraid, with current implementation the only possible way is to `alias` the other factory, and use `build` explicitly on it.

Just to give you an example, your updated code should look like:

```elixir
defmodule Myapp.UserFactory do
  use ExMachina.Ecto, repo: Myapp.Repo

  def user_factory do
    %Myapp.User{
      name: "John"
    }
  end
end

defmodule Myapp.ArticleFactory do
  use ExMachina.Ecto, repo: Myapp.Repo
  alias Myapp.UserFactory

  def article_factory do
    %Myapp.Article{
      title: "Hello",
      user: UserFactory.build(:user)
    }
  end
end
```

Could you confirm it works for you? Hope that helps!

**Comment by paulcsmith** [comment]
@pdawczak Thank you for sharing that snippet. @maxsalven Can you confirm that this worked for your use case?

I'm going to assume it did and close this, but if it didn't, please comment and let us know what you're running in to

**Comment by williamweckl** [comment]
@maxsalven how did you import those files to both user_factory and article_factory can be used?
