### ISSUE TITLE
Could not start application ex_machina: could not find application file: ex_machina.app

### ISSUE THREAD

**Issue by denispeplin** [thoughtbot/ex_machina#156]
Added `{:ex_machina, "~> 1.0", only: :test}`, got this error:

```
$ mix phoenix.server
Compiling 18 files (.ex)
Generated my_app app
[info] Application postgrex exited: :stopped
[info] Application db_connection exited: :stopped
[info] Application connection exited: :stopped
[info] Application phoenix_ecto exited: :stopped
[info] Application ecto exited: :stopped
[info] Application poolboy exited: :stopped
[info] Application decimal exited: :stopped
[info] Application gettext exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application phoenix_html exited: :stopped
[info] Application phoenix_pubsub exited: :stopped

=INFO REPORT==== 17-Aug-2016::11:41:51 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application ex_machina: could not find application file: ex_machina.app
```

After removing `only: test` it works.

**Comment by pdawczak** [comment]
Hi @denispeplin,

Yes, that's correct. In case you use ExMachina with Phoenix (which I guess by using the option `only: test`), you are unable to boot the server up, as ExMachina is not available in development environment.

Please use

```elixir
{:ok, _} = Application.ensure_all_started(:ex_machina)
```

at the very beginning of your **test/test_helper.exs**.

This might need a bit of rework of the documentation.

Hope that solves your problem!

**Comment by denispeplin** [comment]
I've already added this string to `test/test_helper.exs`.
So, if I'm adding `only: test` into `deps`, it breaks my development environment. I can't start server. Is this is really was expected?

**Comment by pdawczak** [comment]
@denispeplin, my apologies, I wasn't clear - for Phoenix you should not include `:ex_machina` in your `:applications`, so if you've done this step:

```elixir
def application do
  [mod: {MyApp, []},
   applications: [:ex_machina, :other_apps...]]
end
```

Please remove `:ex_machina`. The code in **test/test_helper.exs** is only required.

**Comment by denispeplin** [comment]
Great, not it works in both environments! Thank you!

I think its my fault, but it probably won't hurt to add something like this into documentation:

**Do not** add `:ex_machina` into application list!

**Comment by jsteiner** [comment]
Hey @denispeplin, I'm glad you figured it out!

I'm a little hesitant to add it to the documentation just yet, since there's a lot of things you should _not_ do, and I want to keep the documentation focused on what you _do_ need to do. For people googling that error, they should be able to find this thread.

If people continue to have this issue we can reevaluate adding it to the docs.

**Comment by corroded** [comment]
I did find this thread thanks! It would actually help though to remove it from the docs. I think I was [following this](https://robots.thoughtbot.com/building-a-phoenix-json-api) and eventually ended up in [ex machina's docs](https://github.com/thoughtbot/ex_machina) which still has it
