### ISSUE TITLE
use ExMachina.Ecto defines functions with no local return

### ISSUE THREAD

**Issue by KronicDeth** [thoughtbot/ex_machina#157]
In `test/support/factory.ex`, I have

```
  use ExMachina.Ecto., repo: MyApp.Repo
```

This works for the factories just fine, but `mix dialyze` thinks all function defined by the `use` have no local return:

```
test/support/factory.ex:22: Function create/1 has no local return

test/support/factory.ex:22: Function create/2 has no local return

test/support/factory.ex:22: Function create_list/3 has no local return

test/support/factory.ex:22: Function create_pair/2 has no local return

test/support/factory.ex:22: Function fields_for/1 has no local return
```

My work-around is 

```
 @dialyzer {:no_return, create: 1, create: 2, create_list: 3, create_pair: 2, fields_for: 1}
```

Since the functions are only there to raise errors, their specs can say as much as the work-around would not be necessary.  I'll open a PR to do that.

**Comment by KronicDeth** [comment]
It turned out more complex than just those warnings because those were from Erlang 18.3 and Erlang 19.0+ gets a lot better dialyzer for maps, so there are more warnings on 19.0 that you're using on CircleCI.  I can open a PR for just the 18.3 changes if you want.

**Comment by paulcsmith** [comment]
Yeah I think just the changed for 18.3 would be a great start. Thanks so much for catching those :)

**Comment by jsteiner** [comment]
@KronicDeth I'm going to close this for now, although we're more than willing to accept a PR for this if you get around to it.
