### ISSUE TITLE
Example in README causes an infinite loop

### ISSUE THREAD

**Issue by JackOddy** [thoughtbot/ex_machina#161]
```elixir
def user_factory do
    %MyApp.User{
      name: "Jane Smith",
      email: sequence(:email, &"email-#{&1}@example.com"),
    }
end
def article_factory do
    %MyApp.Article{
      title: "Use ExMachina!",
      comments: [build(:comment)],
      author: build(:user),
    }
end

def comment_factory do
  %MyApp.Comment{
    text: "It's great!",
    article: build(:article),
  }
end
```

creates an infinite loop where both comment and article factories constantly call each other - at least that's what happened when we tried it

**Comment by leondewey** [comment]
I'm having the same issue.

**Comment by JackOddy** [comment]
Depending on what you want to do you can get around it like this:

```elixir
def user_factory do
    %User{
      email: "testingemail@test.com",
      password: "password",
      username: "testytest",
      high_score: 1,
      bike: %MyApp.Bike{ 
            color: "green",
            size: "small",
            }
    }
  end
```
I feel like its not how its intended to be used though

**Comment by jsteiner** [comment]
Thanks for the heads up! We've fixed this in the README.

For what it's worth, we rarely set has_many associations in the factory for this situation exactly. Also, factories should be the bare minimum to get a valid object, and it's a rare case that you need to require a has_many association.
