### ISSUE TITLE
has many associations not loaded with params_with_assocs

### ISSUE THREAD

**Issue by jbhatab** [thoughtbot/ex_machina#169]
Here's my factory

```
def registering_company_factory do
  %Company{
    name: sequence(:name, &"Company #{&1}"),
    email: sequence(:email, &"company-#{&1}@example.com"),
    category: Company.categories |> Enum.random,
    users: [
      %{
        role: Enum.random(User.roles),
      }
    ]
  }
end
```

And I'm calling params_with_assocs(:registering_company) but it only spits out,

%{
  active: nil
  address: nil
  category: "Cultivator"
  description: nil
  email: "company-0@example.com"
  inserted_at: nil
  latitude: nil
  longitude: nil
  name: "Company 0"
  official: nil
  permalinks: [
  ]
  phone: nil
  updated_at: nil
}

Is there a way to load associations with the params call?

**Comment by hisapy** [comment]
Hey guys,

I'm having this problem with `has_many` associations. For example, I have something like the following 

```elixir
defmodule Webapp.SomeStuff do
  schema "some_stuffs" do
    has_many :other_stuffs, Webapp.OtherStuff
  end
end

# and in the news schema
defmodule Webapp.OtherStuff do
  schema "other_stuffs" do
    belongs_to :some_stuff, Webapp.SomeStuff
    # other fields
  end
end

# the factories look look like
def some_stuff_factory do
  %Webapp.SomeStuff{
    news: [build(:other_stuff)]
  }
end

def other_stuff_factory do 
  %Webapp.OtherStuff{
    # fields here
  }
end
```

But when I call `params_with_assoc(:some_stuff)` or `string_params_with_assoc(:some_stuff)` I just get`other_stuffs: [%{}]`. 

`insert` and `build` seem to work just fine.

I'm using **ExMachina v2.1.0**
