### ISSUE TITLE
Master branch incorrectly cast values on `insert`

### ISSUE THREAD

**Issue by hauleth** [thoughtbot/ex_machina#171]
I have bunch of custom types that are casted to integers during insertion. In released version `1.0.2` there is no such problem.

## Example:

I have cusom Ecto type that works like enum and when I `insert` data then it happens to be all converted to integers while I would expect strings (this is what is returned when I refetch data using `Repo`).

**Comment by jsteiner** [comment]
@hauleth would you mind pasting your factory definition, the model, the custom Ecto type definition, and the test?

**Comment by hauleth** [comment]
No longer problem. It was some kind of issue on my side. Sorry for inconveniences.

**Comment by paulcsmith** [comment]
Awesome! I'm glad you figured out a solution :)
