### ISSUE TITLE
Need a way to customize Ecto structs beyond Map merging

### ISSUE THREAD

**Issue by jeffdeville** [thoughtbot/ex_machina#175]
I hit a snag when building a multi-tenant solution.  I need to be able to set the prefix when I insert an object.  Something like:

`insert(:user, "tenant_test")`

Problem is that Ecto stores this info in the Ecto.Schema.Metadata.source tuple as {prefix, table_name}

Tuples can't be merged like structs, so Ecto provides: 

`Ecto.put_meta(model, prefix: prefix)`

So the bottom line is that I need to be able to make this call while invoking the insert command.

**Comment by paulcsmith** [comment]
I would take a look at `https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina/strategy.ex` and make a custom strategy. You could do something like

`insert_with_tenant(:user, prefix: "tenant_test")` and in your strategy you could grab the prefix from the attrs. Strategies let you do almost anything you want.

LMK if this helps or if you need help figuring out how to use a strategy for this
