### ISSUE TITLE
params_for returns updated_at and inserted_at

### ISSUE THREAD

**Issue by digitalcake** [thoughtbot/ex_machina#177]
Not really sure if there is a better way to do this but it would look like at first glance params_for returns attributes that are not useful 

In phoenix we have generated controller specs.  If I was to replace the `@valid_attrs` assignment with  `@valid_attrs params_for(:post)` and re run the test I get an error such as.

`** (ArgumentError) nil given for :inserted_at. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.inserted_at)`

A solution is to remove `inserted_at` and `updated_at`  via. 

`@valid_attrs params_for(:post) |>  Map.drop([:inserted_at, :updated_at]`

How useful is it for params_for to return the ectos model timestamps()?

**Comment by pdawczak** [comment]
This is interesting - which version of ExMachina do you use?

Could you also provide your factory definition? Thanks!

**Comment by yknx4** [comment]
+1

**Comment by paulcsmith** [comment]
I'm not sure I understand. If the app crashes because inserted_at and updated_at are nil, then it seems like the (changeset/controller/whatever is handling the params) should filter out those nil values. It would be helpful if you include an example of the controller/changeset where the issue shows up

**Comment by digitalcake** [comment]
mix.lock
```"ex_machina": {:hex, :ex_machina, "1.0.2", "1cc49e1a09e3f7ab2ecb630c17f14c2872dc4ec145d6d05a9c3621936a63e34f", [:mix], [{:ecto, "~> 2.0", [hex: :ecto, optional: true]}]},
```

test/support/factory.ex
```
defmodule Opalnova.Factory do
  # with Ecto
  use ExMachina.Ecto, repo: Opalnova.Repo

  def user_factory do
    %MyApp.User{
      name: "Jane Smith",
      email: sequence(:email, &"email-#{&1}@example.com"),
      password: "password",
      password_confirmation: "password"
    }
  end
end
```

iex -S mix 
```
    
iex(1)> c "test/support/factory.ex"
[Opalnova.Factory]
iex(2)> import Opalnova.Factory
Opalnova.Factory
iex(3)> params_for(:user)
%{email: "email-0@example.com", inserted_at: nil, name: "Jane Smith",
  password: "password", password_confirmation: "password", password_hash: nil,
  updated_at: nil}
```

**Comment by narugami** [comment]
@digitalcake 
Don't use Hex and pull from this master.
For details, see #186 .

**Comment by narugami** [comment]
In 1.0.2 on Hex, drop_fields_with_nil_values is not defined.
You will solve this issue by using 1.0.2 on GitHub.

**Comment by paulcsmith** [comment]
@digitalcake Did @narugami's suggestion work for you?

**Comment by narugami** [comment]
@paulcsmith Can you update the hex repo?
I wish 1.0.2 on GitHub and one on Hex are identical.

**Comment by digitalcake** [comment]
So it looks like 1.0.2 on github master fixed this issue. Thanks.
