### ISSUE TITLE
Refer to own properties?

### ISSUE THREAD

**Issue by brandonparsons** [thoughtbot/ex_machina#178]
Hi there,

Just wondering if there's any way in ExMachina to specify an attribute to be a function of another attribute in the same factory. There's ways to get this done in FactoryGirl, wondering if it's the same over here.

For example, a `User` has a `name` property, which we set using ExMachina's `sequence` function. Further down in this factory, I'd like to reference this name when setting the email for the `User.`

I tried pulling the specification of `name` to the top of the factory, and referring to that later. This works on initial build/inserts, but if you try to use a keyword list to change the default `name` property it doesn't work properly.

Any help you could provide would be appreciated!

**Comment by jsteiner** [comment]
Hey @brandonparsons! There's an existing [issue](https://github.com/thoughtbot/ex_machina/issues/130) and [PR](https://github.com/thoughtbot/ex_machina/pull/131) for this feature, so I'm going to close this one to keep the conversation focused on those threads.

We're still debating whether we want to support this functionality, but last I spoke to @paulcsmith we were leaning towards yes.
