### ISSUE TITLE
Give factory methods access to caller provided attributes (if any)

### ISSUE THREAD

**Issue by jakesgordon** [thoughtbot/ex_machina#180]
Thanks for the great library!

When writing my factory methods I find myself wishing I knew which attributes the caller is overriding because some generated attributes might be best derived from other attributes.

For example, if I currently want my `user.email` to be derived from my `user.name` I might do this ...

    def user_factory do
      name = "jake"
      %User{
        name: name,
        email: "#{name}@domain.com"
      }
    end

But if my test builds with a different `name`...

    build(:user, name: "bob")

Then I end up with an inconsistent user who's name is **bob** but email is **jake**@domain.com

We could write smarter factory methods if we had access to the caller provided `attr`, so I could write

    def user_factory(attr) do
      name = attr.name || "jake"
      %User{
        name: name,
        email: "#{name}@domain.com"
      }
    end

Does that make sense?

I'd be happy to make this change and create a PR.

Thanks!

**Comment by paulcsmith** [comment]
I think this would be covered by #130. Going to close this in favor of that issue. If I got it wrong though, please let me know and I'll re-open this with an explanation of what's different!
