### ISSUE TITLE
Ecto 2.1.0-rc.* dependency

### ISSUE THREAD

**Issue by andreapavoni** [thoughtbot/ex_machina#182]
Hi all,

Is it possible to update dependency requirement for the upcoming Ecto 2.1.0?

I'm going to fork the repo and try forcing the dependency to 2.1.0-rc.4

thanks for the awesome work ;-)

**Comment by lasseebert** [comment]
Ecto 2.1.0 is now out :)

**Comment by lasseebert** [comment]
I have begun updating my app to Ecto 2.1.0.

It seems that ex_machina works out of the box.
But oif I change my factories to use `DateTime.utc_now` instead of `Ecto.DateTime.utc` I get the following error:

```
** (Ecto.ChangeError) value `%DateTime{calendar: Calendar.ISO, day: 17, hour: 22, microsecond: {169798, 6}, minute: 39, month: 12, second: 34, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2016, zone_abbr: "UTC"}` for `MyApp.SomeModel.some_timestamp` in `insert` does not match type Ecto.DateTime
```

**Comment by lasseebert** [comment]
I should note that my models now use the new `utc_datetime` type for timestamp fields.

Assume a model `User` with field `activated_at`

With this factory:

```elixir
def user_factory do
  %MyApp.User{
    name: "User Userson",
    activated_at: Ecto.DateTime.utc
  }
end
```

my tests run just fine. Even if I `insert` with a `DateTime` like so:

```elixir
insert(:user, activated_at: DateTime.utc_now)
```

But with this updated factory:

```elixir
def user_factory do
  %MyApp.User{
    name: "User Userson",
    activated_at: DateTime.utc_now
  }
end
```

I get the error described in my comment above.

**Comment by jsteiner** [comment]
@lasseebert we haven't released a new version yet, but if you use the latest ex_machina from github, we automatically cast values for you. I think that should fix the issue you're seeing.

**Comment by lasseebert** [comment]
@jsteiner, cool thx. Will try it out tomorrow 😊

**Comment by lasseebert** [comment]
@jsteiner. Well this is embarrassing. I made the changes to my factories again. Expected the tests to fail before using the master version from github, but they didn't.

Not sure what happened. Perhaps some compiled deps that wasn't recompiled.

I think this issue can be closed ;) Thanks for the help.

**Comment by paulcsmith** [comment]
@lasseebert Awesome! So glad it's working out fine now. Sometimes the compiler caches things it should and it's always a bummer when you find out after a few hours of head banging :P
