### ISSUE TITLE
Hex version (1.0.2) is missing fix

### ISSUE THREAD

**Issue by expede** [thoughtbot/ex_machina#186]
Hi! First off, thanks for all of the wonderful libraries. I am a huge fan of ExMachina, and FactoryGirl before it 😄 

I realize that this was brought up in #170 back in October, so this is just a friendly request to publish a `1.0.3`.

We're using `1.0.2` (most current on Hex), which hasn't seen a version bump since the summer. There's a fix on `master`for not dropping autogenerated IDs from `params_for`. We've switched to pulling the package from GitHub, but wanted to let you know in case anyone else runs into similar problems.

Relevant code: [`master`](https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina/ecto.ex#L179-L190) & [`1.0.2`](https://github.com/thoughtbot/ex_machina/blob/d6ff56ee566cb29cbec5831698a0b06b88f91e63/lib/ex_machina/ecto.ex#L124)

Cheers!

**Comment by tessi** [comment]
You are not alone, we have the same problem at my company ;)

@jsteiner @paulcsmith Is there something we can do (like updating the changelog in a PR) to help you release a new version?

**Comment by PragTob** [comment]
:+1: happy to help compile a Changelog or whatever might be needed :)

**Comment by paulcsmith** [comment]
That would be very helpful! If ou could submit a PR that would be incredible. I've been a bit busy with other things so I'd really appreciate it :D

**Comment by jsteiner** [comment]
Thanks for being patient everyone! I had some time this week to do a little clean up and [update the changelog](https://github.com/thoughtbot/ex_machina/pull/194) in preparation for 2.0.

Once my other PRs get merged, we'll have to do a little more testing on our own projects, and perhaps request some of you to test them on your projects before releasing.

**Comment by paulcsmith** [comment]
We're prepping for release of 2.0. It's on master. If people on this thread could give it a go that would be really great. We're testing it internally and if all is well we'll push it up to hex

**Comment by tessi** [comment]
the current master (` f003eb3`) works perfectly for my app. ❤️  thanks for your work

**Comment by paulcsmith** [comment]
Hi everyone. `2.0.0` is out on hex! https://github.com/thoughtbot/ex_machina/commit/9869fb5a7d8fff8b99715a718aa74c27a5a13741 and https://hex.pm/packages/ex_machina :D
