### ISSUE TITLE
`sequence` error

### ISSUE THREAD

**Issue by icn** [thoughtbot/ex_machina#187]
I got his error when I tried to use `sequence`
```

     ** (exit) exited in: GenServer.call(ExMachina.Sequence, {:get_and_update, #Function<0.22382681/1 in ExMachina.Sequence.next/2>}, 5000)
         ** (EXIT) no process
```

This is how I used it

```
defmodule Bwe.Factory do
  use ExMachina.Ecto, repo: Bwe.Repo
  alias Bwe.User

def user_factory do
  %User{
    email: sequence(:email, &"email-#{&1}@example.com"),
    name: "f lastname",
  }
end

end
```

**Comment by tsubery** [comment]
Is it possible you don't have :ex_machina defined in your mix file application list?

**Comment by pdawczak** [comment]
From the error you've pasted it looks like `ExMachina` is not up and running, you can do either:

  * Include it in your `applications`:

```elixir
# mix.exs
def application do
  [mod: {MyApp, []},
   applications: [:ex_machina, :other_apps...]]
end
```

  * Start it manually if you intend to use it in `test` environment only:

```
# test/test_helper.exs
{:ok, _} = Application.ensure_all_started(:ex_machina)
```

**Comment by icn** [comment]
Hi @pdawczak  Thanks a lot for helping!  I forgot to include `:ex_machina` in the 

```
def application do
  [mod: {MyApp, []},
   applications: [:ex_machina, :other_apps...]]
end
```

Now I can use `sequence` in my factory.

Thanks again!

**Comment by blakedietz** [comment]
After phoenix 1.4 the above solution is no longer valid. Do not define ex_machina for applications or extra_applications.
