### ISSUE TITLE
params_with_assocs behaves inconsistently

### ISSUE THREAD

**Issue by vraravam** [thoughtbot/ex_machina#190]
In my phoenix app, I have 2 models: Candidate and Interview with the relationship as: `interview belongs_to :candidate`. When using ExMachina, I see the following, imo inconsistent, behavior:

```elixir
iex(33)> candidate = MyApp.Factory.insert(:candidate)
iex(34)> interview = MyApp.Factory.params_with_assocs(:interview)
%{candidate_id: 43125,
  end_time: #<DateTime(2017-01-11T07:30:38.144475Z Etc/UTC)>, inserted_at: nil,
  interview_type_id: 48529,
  start_time: #<DateTime(2017-01-11T05:30:38.144475Z Etc/UTC)>, updated_at: nil}
iex(35)> interview = MyApp.Factory.params_with_assocs(:interview, candidate: candidate)
%{end_time: #<DateTime(2017-01-11T07:30:49.287469Z Etc/UTC)>, inserted_at: nil,
  interview_type_id: 48530,
  start_time: #<DateTime(2017-01-11T05:30:49.287469Z Etc/UTC)>, updated_at: nil}
```

As you can see, the `candidate_id` is *not* injected into the returned Map when I specify the `candidate` associated object; whereas it is injected automatically in the returned Map when I let the factory build it. Isn't this a bug? If so, I would really appreciate it if you could fix it asap.

**Comment by paulcsmith** [comment]
I believe this was closed by #174. If not, please re-open. Thanks!
