### ISSUE TITLE
protocol Enumerable not implemented for nil

### ISSUE THREAD

**Issue by vraravam** [thoughtbot/ex_machina#191]
Using the latest master of this repo (d2d901e12), my specs fail with the following error:
```elixir
	** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    (elixir) lib/enum.ex:1188: Enum.map/2
    (ex_machina) lib/ex_machina/ecto_strategy.ex:74: anonymous fn/2 in ExMachina.EctoStrategy.cast_all_assocs/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_machina) lib/ex_machina/ecto_strategy.ex:17: ExMachina.EctoStrategy.handle_insert/2
```
Please fix asap.

**Comment by jsteiner** [comment]
Can you provide more info on the failing spec, such as the spec and any relevant factories.

**Comment by vraravam** [comment]
@jsteiner - The whole codebase is open source. The specific factory is [here](https://github.com/TWChennai/RecruitX-Backend/blob/master/spec/support/factory.ex).

**Comment by jsteiner** [comment]
I've added a failing test to reproduce this here: https://github.com/thoughtbot/ex_machina/compare/js-nil
