### ISSUE TITLE
undefined function insert/1

### ISSUE THREAD

**Issue by bentobenti** [thoughtbot/ex_machina#197]
I've been following trying to do the **Building and testing a Phoenix JSON API** thoughtbot tutorial but I'm stuck at the following error:

```
(CompileError) test/controllers/todo_controller_test.exs:7: undefined function insert/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

I'm pretty new to elixir and even more so to phoenix so it's probably a newbie mistake.  Some help would be very much be appreciated.

**Comment by pdawczak** [comment]
From this error is quite difficult to diagnose... My first thought - is
your factory file extension `.exs` or `.ex`?

**Comment by bentobenti** [comment]
It's ` .ex `

**Comment by pdawczak** [comment]
Ok, that's good then. Are you including the Factory module in your test
module? Might be useful if you've dropped content of the controller test
file here for us to discuss.

**Comment by bentobenti** [comment]
```
defmodule App.TodoControllerTest do
  use App.ConnCase

  test "#index renders a list of todos" do
    conn = build_conn()
    todo = insert(:todo)

    conn = get conn, todo_path(conn, :index)

    assert json_response(conn, 200) == %{
      "todos" => [%{
        "title" => todo.title,
        "description" => todo.description,
        "inserted_at" => Ecto.DateTime.to_iso8601(todo.inserted_at),
        "updated_at" => Ecto.DateTime.to_iso8601(todo.updated_at)
      }]
    }
  end
end

```

it's basically taken right of the tutorial, unless I made a silly mistake

**Comment by pdawczak** [comment]
Could you try adding one import of the Factory you've defined to your test file?

Something like:

```elixir
defmodule App.TodoControllerTest do
  use App.ConnCase
  import App.Factory # <-- use the name of the factory module you've created, this is most likely `App.Factory`

  # ...

end
```

Did that help?

**Comment by bentobenti** [comment]
ah it seemed to work! I'm getting a new error but it's consistent with what the tutorial was explaining. Thank you for you help.
Seems like I'm missing some knowledge as to how module, methods are passed around could you please explain me why this was necessary or point to some related documentation :)

**Comment by pdawczak** [comment]
Glad I could help.

This very _issue_ is not related to ExMachina, but it's rather an asset of Elixir, so I'd suggest reading how `import`s/`alias`es work in the language, and the official page seems to be good starting point - http://elixir-lang.org/getting-started/alias-require-and-import.html#import

Hope this clarifies things!

**Comment by paulcsmith** [comment]
Thanks for helping with this issue @pdawczak. I'm glad you got it working @bentobenti

**Comment by vespertilian** [comment]
@bentobenti 

Was you new error: 

```** (FunctionClauseError) no function clause matching in Ecto.DateTime.to_iso8601/1```

and did you work out how to fix it. I'm also new.

**Comment by bentobenti** [comment]
Yes I'm having this issue wasn't able to solve it. I'm taking a break from the tutorial to read the elixir documentation if I solve it I'll try to notify on this thread.

**Comment by bentobenti** [comment]
@vespertilian making it work actually required casting the todo datetime fields to an accepted Ecto.DateTime format.
the `(FunctionClauseError)` occurs when you're using a defined function but you're passing it an incorrect type

you can fix it by doing something like this 
```
    casted_inserted = Ecto.DateTime.cast!(todo.inserted_at)
    casted_updated = Ecto.DateTime.cast!(todo.updated_at)
```

and use the newly created variables in your assertion.

Note: I found 2 cast functions inside the Ecto documentation the first 
`cast` is supposed to take a variety of datetime format and out put an Ecto.DateTime format
the second
`cast!` is supposed to be the same as the first one except it raises an error when it is passed invalid datetimes
I tried with `cast` first but it wasn't working

**Comment by vespertilian** [comment]
@bentobenti, Ok thanks! I will try that out.

**Comment by andela-idurotola** [comment]
Trying the above resulted in another error. @vespertilian did it work for you ?
I got this `#Ecto.DateTime<2017-03-04 16:33:44.716103>` which does not match the string `"2017-03-04T16:33:44.716103"`

**Comment by vespertilian** [comment]
@andela-idurotola I have not got back to it yet.. I think I need to work on the fundamentals of Elixir first.

**Comment by alemangui** [comment]
@andela-idurotola, @vespertilian, The reason you got 

```
#Ecto.DateTime<2017-03-04 16:33:44.716103>
```

is because the ```cast!``` function transforms the parameter into an ```Ecto.DateTime``` object. You are looking for a string representation of that object in ISO8601 format.

Now that you have the ```Ecto.DateTime```, you can call the ```to_iso8601``` function on it. It would look like this:

```
inserted_at => Ecto.DateTime.cast!(todo.inserted_at) |> Ecto.DateTime.to_iso8601
```
