### ISSUE TITLE
Association gets inserted twice when it related to another

### ISSUE THREAD

**Issue by edevil** [thoughtbot/ex_machina#213]
I have the following data model:

```
  schema "clients" do
    field :name, :string
    has_many :users, Trendex.User
  end

  schema "users" do
    field :name, :string
    belongs_to :client, Trendex.Client
  end

  schema "invitations" do
    field :name, :string
    belongs_to :user, Trendex.User
    belongs_to :client, Trendex.Client
  end
```

and the following factories:
```
def client_factory do
    %Client{
      name: sequence(:name, &"clientname#{&1}")
    }
  end

def user_factory do
    %User{
      client: build(:client),
      name: sequence(:name, &"username#{&1}")
    }
  end

  def invitation_factory do
    user = build(:user)
    %Invitation{
      name: sequence(:name, &"name#{&1}"),
      client: user.client,
      user: user
    }
  end
```

When I try to ```insert(:invitation)``` the same client is inserted twice which is an integrity violation, since 2 clients cannot have the same name. Am I doing something wrong or is this scenario not supported?

Do I need to manually clean the "client" association from user in the invitation factory since client is also one of the attributes?

**Comment by schrockwell** [comment]
This appears to be a misunderstanding in how Ecto works, and not a bug in `ex_machina`. Think about the result of `build(:invitation)` before doing the insert:

```
%Invitation{
  id: nil,
  name: "name1",
  client: %Client{
    id: nil,
    name: "clientname1"
  },
  user: %User{
    id: nil,
    client: %Client{
      id: nil,
      name: "clientname1"
    }
  }
}
```

Note that Ecto will attempt to insert two clients with the same name since their `id`s are both `nil`.

What you want to do instead is `insert` that user (and, hence, its client) so that the foreign keys can be set up correctly:

```
  def invitation_factory do
    user = insert(:user) # <-- changed
    %Invitation{
      name: sequence(:name, &"name#{&1}"),
      client: user.client,
      user: user
    }
  end
```

Now you will have this, which Ecto knows how to deal with:

```
%Invitation{
  id: nil,
  name: "name1",
  client: %Client{
    id: 1,
    name: "clientname1"
  },
  user: %User{
    id: 1,
    client: %Client{
      id: 1,
      name: "clientname1"
    }
  }
}
```

**Comment by germsvel** [comment]
Thanks for that explanation @schrockwell! Very helpful. @edevil does that solve the issue you were having?

**Comment by edevil** [comment]
Thanks for the help. I still haven't been able to test this but I'll try to do it in the next few days and report back.

**Comment by edevil** [comment]
I can no longer reproduce this issue, it's been a few months already away from the project. I'll close this for now and if I ever run into this issue again I'll return. Thanks. :)
