### ISSUE TITLE
Add start_at: option to sequences

### ISSUE THREAD

**Issue by camcaine** [thoughtbot/ex_machina#214]
When using sequences I occasionally find myself wanting to start the sequence from a value other than zero. The solution I came up with was to change `sequence/1` to work like this:

`sequence("cameron", start_at: 1)`
`sequence({:name, & "cameron" <> &1}, start_at: 100)`

It introduces a breaking change removing `sequence/2` and using a tuple to pass a formatter instead. This seemed like the most idiomatic way while implementing it.

Pull request tested and ready if this would be a useful addition?

**Comment by germsvel** [comment]
Thanks for bringing this up @camcaine. I usually think of using sequences when I want to make sure I don't run into uniqueness validations in my tests, but I haven't run into a scenario where I want to control the starting point. 

Do you have a use case that could help me understand when you need to control the starting point?

**Comment by Trevoke** [comment]
We have a case where `0` is a default / fallback value with a special meaning, so it's a problem to have sequences start at 0.

**Comment by germsvel** [comment]
It's been a while, but I recently looped back to this, and I realize the change is quite simple. If you're still interested in this, I opened PR for this work, and I'd love to hear your thoughts. https://github.com/thoughtbot/ex_machina/pull/414

**Comment by Trevoke** [comment]
It's everything I hoped to see :)
