### ISSUE TITLE
string_params_for should cast embeddings into maps

### ISSUE THREAD

**Issue by Sitch** [thoughtbot/ex_machina#215]
Lets say you have a `Car` that `embeds_one` `Engine`.

```elixir
def car_factory do
  %Car{
    engine: build(:engine)
  }
end
```
if you call `string_params_for`, the nesting will still have a struct typed `Engine` instead of a plain map. i.e:

```elixir
%{
  "engine" => %Engine{ ... }
}
```
not
```elixir
%{
  "engine" => %{ ... }
}
```

**Comment by germsvel** [comment]
Hi @Sitch, I find that a little counterintuitive since `string_params_for(:car)` doesn't give me `%Car{}` with string keys but `%{}` with string keys. So if that's the behavior at the top level, I would think we would keep that behavior consistent when dealing with nested structures. What do you think?

**Comment by Sitch** [comment]
@germsvel the use case for this post was getting a semi-deep nested json payload from a 3rd party provider.  For me, it was useful to not have to write the same factory in two different ways (one version with typed nested structures and one version that represented the json decoding with string keys).  Additionally, the rational in the docs for `string_params_for` is phoenix controllers, which would not implicitly type cast those nested arguments

**Comment by germsvel** [comment]
@Sitch I'm sorry. I misread your original post. I thought you _wanted_ `string_params_for/2` to give, 

```elixir
%{
  "engine" => %Engine{ ... }
}
```

I have now read it correctly. You're saying that's the _current_ behavior, but that instead it should give you something like this, 

```elixir
 %{
  "engine" => %{ ... }
}
```

I agree. Sorry for the confusion.

**Comment by Sitch** [comment]
@germsvel no worries -- gotta work on my verbal clarity 👓.  Let me know if you want help with the PR

**Comment by germsvel** [comment]
@Sitch thinking about it, I actually think https://github.com/thoughtbot/ex_machina/pull/224 will fix this issue.

**Comment by germsvel** [comment]
I believe #224 closes this. If not, please re-open. Thank you for reporting this!
