### ISSUE TITLE
Multiple repos

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/ex_machina#217]
It it possible to use ExMachina with multiple repos for a single factory definition?

**Comment by paulcsmith** [comment]
@anthonator right now, no there is not. Usually when I've had multiple repos I I've had different tables in each so it hasn't been an issue. Can you describe what you are trying to do? Maybe there's a workaround

**Comment by szsoppa** [comment]
@anthonator I can describe you why I need this support. I'm using [Shield](https://github.com/mustafaturan/shield) library to protect my api with oauth2 protocol. It uses it's own repo for `User` model. I also have `Timetable` which is being handled by Repo from my own project, and it has an association with `User`. I need to create timetable factory with given user.

**Comment by paulcsmith** [comment]
@szsoppa Thanks for posting. can you also paste the factory definition so I can better idea of what your factories look like?

**Comment by szsoppa** [comment]
I'm sorry, my issue was not related with multiple repos.

**Comment by germsvel** [comment]
@anthonator I'm going to close this issue. If you want to revisit this please let me know, and we can certainly reopen it!

@szsoppa thanks for commenting back and letting us know that your issue was not related to multiple repos.

**Comment by ylansegal** [comment]
So far, I've had success using multiple repos by explicitly inserting into the appropriate repo:

```elixir
build(:user) |> LegacyRepo.insert()
build(:user) |> AnotherRepo.insert()
```

**Comment by aizotov** [comment]
> So far, I've had success using multiple repos by explicitly inserting into the appropriate repo:
> 
> ```elixir
> build(:user) |> LegacyRepo.insert()
> build(:user) |> AnotherRepo.insert()
> ```

This works but causes issues in async tests.

**Comment by PJUllrich** [comment]
I'm late to the discussion, but I wanted to share my solution as well :) 

Basically, I put an interface between the ExMachina Factories and delegate any `insert, insert_pair, insert_list, params_for` calls to the correct Factory based on the factory name.

So, this e.g. is my generic Factory:

```elixir
# test/support/factory.ex

defmodule Support.Factory do
  alias Support.Factories.Legacy
  alias Support.Factories.Another

  def insert(type, attrs \\ [], opts \\ []) do
    factory = get_factory(type)
    factory.insert(type, attrs, opts)
  end

  def insert_pair(type, attrs \\ []) do
    factory = get_factory(type)
    factory.insert_pair(type, attrs)
  end

  def insert_list(count, type, attrs \\ []) do
    factory = get_factory(type)
    factory.insert_list(count, type, attrs)
  end

  def params_for(type, attrs \\ []) do
    factory = get_factory(type)
    factory.params_for(type, attrs)
  end

  defp get_factory(type) do
    cond do
      type in [:legacy_type, :another_legacy_type] -> Legacy
      type in [:new_type, :another_new_type] -> Another
    end
  end
end
```

Then, in my e.g. `ConnCase`, I simply import the interface factory with `import Support.Factory`.

In my tests, I can now simply call the factory functions without having to worry which Factory handles the schema type.

```elixir
test "foo" do
  insert(:legacy_type)
  insert(:new_type)
end
```
