### ISSUE TITLE
Cannot define with_xxx factory in split factory files

### ISSUE THREAD

**Issue by Draveness** [thoughtbot/ex_machina#219]
Here are the files related to ex_machina

```elixir
#  test/factories/user_factory.ex
defmodule Instant.UserFactory do
  alias Instant.User
  defmacro __using__(_opts) do
    quote do
      def user_factory do
        %User{
          username: Faker.Internet.user_name,
          password: "password",
          password_confirmation: "password",
          password_hash: Comeonin.Bcrypt.hashpwsalt("password")
        }
      end

      def with_conversations(user) do
        insert_pair(:conversation, user1: user)
        user
      end
    end
  end
end

# test/factories/conversation_factory.ex
defmodule Instant.ConversationFactory do
  alias Instant.Conversation
  defmacro __using__(_opts) do
    quote do
      def conversation_factory do
        %Conversation{
          user1: build(:user),
          user2: build(:user)
        }
      end
    end
  end
end

# test/factory.ex
defmodule Instant.Factory do
  use ExMachina.Ecto, repo: Instant.Repo
  use Instant.UserFactory
  use Instant.ConversationFactory
end
```

And in test file

```elixir
  setup %{conn: conn} do
    user = build :user
    |> insert
    |> with_conversations
    ....
  end
```

When running `mix test` in the terminal, it complains about argument error:

```elixir
** (ArgumentError) argument error
stacktrace:
:erlang.atom_to_binary(%Instant.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, conversations: #Ecto.Association.NotLoaded<association :conversations is not loaded>, id: 1123, ...}, :utf8)
(ex_machina) lib/ex_machina.ex:144: ExMachina.build/3
test/controllers/message_controller_test.exs:9: Instant.MessageControllerTest.__ex_unit_setup_1/1
test/controllers/message_controller_test.exs:1: Instant.MessageControllerTest.__ex_unit__/2
```

It seems like something went wrong here https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina.ex#L144 and ExMachina failed to build factory method with code above, but I follow the README documentation and defined factories just as it tells.

**Comment by germsvel** [comment]
@Draveness I have been trying to reproduce this error in a sandbox app that I created, but have been unsuccessful. 

Are you still experiencing this and/or were you able to find a solution to it? 
If it's still happening, is there any more info you could provide so I can see if I can reproduce it (e.g. the schemas defined in the ecto models)?

**Comment by schrockwell** [comment]
@Draveness I believe this is a syntax problem... you need to put parenthesis around the `build` argument when you're using it in the pipeline with multiple lines like that. Otherwise the pipe operator is trying to operate on the `:user` atom instead of the result of `build()`

```  
  setup %{conn: conn} do
    user = build(:user)   # <-- added parens
    |> insert
    |> with_conversations
    ....
  end
```

**Comment by germsvel** [comment]
@Draveness I'm going to close this for now. Let us know if this is still a problem, and we can reopen it. Thank you @schrockwell for the keen eyes.

**Comment by Draveness** [comment]
But I don’t know whether this is a problem. I didn’t work on this project for a long long time. But still thanks all of you.
