### ISSUE TITLE
Feature Idea: Enums

### ISSUE THREAD

**Issue by bnns** [thoughtbot/ex_machina#223]
It would be great if we could do something like:
```elixir
def role_factory do
  %Role{
    name: enum(["owner", "admin", "guest"])
  }
end
```
which would behave like:
```elixir
build(:role)
# %Role{name: "owner"}
build(:role)
# %Role{name: "admin"}
```

**Comment by pdawczak** [comment]
Wouldn't [`Enum.random/1`](https://hexdocs.pm/elixir/Enum.html#random/1) work for that case?

Something like:

```elixir
Enum.random(["owner", "admin", "guest"])
```

in

```elixir
def role_factory do
  %Role{
    name: Enum.random(["owner", "admin", "guest"])
  }
end
```

**Comment by bnns** [comment]
Yeah, kind of - but I was thinking of cases where you need at least 1 struct for each value. Besides creating a user for each role, another use-case for me is to build a struct per day of the week.

```elixir
def schedule_factory do
  %Schedule{
    day_of_week: enum(["Sun", "Mon", "Tue", ...]),
    start_time: Ecto.Time.cast!("12:00:00Z"),
    end_time: Ecto.Time.cast!("3:00:00Z")
  }
end
```

The ability to go in order would nice for that situation.

**Comment by suhrawardi** [comment]
Please have a look at this PR #227, 

```
def schedule_factory do
  %Schedule{
    day_of_week: sequence(:weekdays, ["Sun", "Mon", "Tue"]),
    start_time: Ecto.Time.cast!("12:00:00Z"),
    end_time: Ecto.Time.cast!("3:00:00Z")
  }
end
```

**Comment by bnns** [comment]
Looks great! Thanks @suhrawardi. Closing this issue.
