### ISSUE TITLE
params_for should cover nested structs

### ISSUE THREAD

**Issue by zimt28** [thoughtbot/ex_machina#226]
Currently `params_for` won't look at nested structs, so we don't end up with a plain map.

```shell
iex(1)> params_for(:shops)
%{address: %App.Shared.Address{city: "City", country_iso: "DE", id: nil,
   postcode: "12345", street: "Steet 1"},
  email_address: "shop.1@mail.com", phone_number: "111111",
  title: "Shop 1"}
```

**Comment by zimt28** [comment]
It [looks like embeds should be taken care of](https://github.com/thoughtbot/ex_machina/blob/40b748d61516fdf84c36af13ae43315ab02f0387/lib/ex_machina/ecto.ex#L155-L159), which doesn't seem to work. I'll look into that later this day

**Comment by fsabe** [comment]
You're looking at the code on `master`. The currently released version (v2.0.0) does not include this change yet.

**Comment by zimt28** [comment]
@fsabe Thanks, I see. I looked at the [mix file](https://github.com/thoughtbot/ex_machina/blob/master/mix.exs#L5 ) before and it says `2.0.0`, so I thought it should be included :) When will the changes be pushed to hex?

**Comment by germsvel** [comment]
@zimt28 since this is fixed in master, I'm going to close this. Let me know if it should be reopened. (I hope the changes will be pushed to hex soon)
