### ISSUE TITLE
Usage in Umbrella Applications

### ISSUE THREAD

**Issue by axelson** [thoughtbot/ex_machina#229]
Are there any special steps we should take for using ExMachina in umbrella applications? I can see it being useful in both the `app_web` and `app` applications. Should the factory be defined in the `app` and then used in both the `app` and `app_web` applications?

**Comment by paulcsmith** [comment]
@axelson I've never used umbrella apps yet so I don't have any good advice about where to put them when used in Umbrella applications. I would post to the Elixir Forum http://elixirforum.com/ or in Elixir Slack https://elixir-slackin.herokuapp.com

Either of those places will probably get you really good answers from people that have used umbrella apps. I hope that helps!
