### ISSUE TITLE
Non deterministic behaviour of changeset error

### ISSUE THREAD

**Issue by szsoppa** [thoughtbot/ex_machina#236]
I have a very strange problem with inserting record which has `has_many` relations.
First of all error message is following:
```
** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.
...
Errors
        %{timetables: ["is invalid"]}
```

My relations are following:

```
schema "users" do
    has_many :timetables, Timetable
end

schema "timetables" do
    belongs_to :user, Authable.Model.User, type: :binary_id
end
```

Maybe it's worth noticing that I'm using [Authable](https://github.com/mustafaturan/authable) library as oauth2 provider (but for that purpose I'm using my project repo).

Factories:

```
def user_factory do
    %User{
      email: sequence(:email, &"foo-#{&1}@example.com"),
      password: CryptUtil.salt_password("qwer1234"),
      settings: %{confirmed: true}
    }
end

def timetable_factory do
    %Timetable{
      ...
      user: build(:user)
    }
end
```

And now the fun begins, if I delete `user: build(:user)` from timetable factory, error won't show up. Then if I clean deps, and get them againg (while in code ` user: build(:user)` is removed) and run tests again I will get the same `Ecto.InvalidChangesetError`. In this case restoring  ` user: build(:user)` helps and error won't show up. Meaning - there are two different version of factory, both of them works, but depending on deps.

**Comment by germsvel** [comment]
Hey @szsoppa it's hard for me to determine what's going on with the details you provided. Are you still running into this problem? And if so, could you show an example of the changeset you are trying to insert?

**Comment by szsoppa** [comment]
@germsvel For now, it's no longer an issue. I think we can close this.
