### ISSUE TITLE
Make `build` work when also importing Ecto.Model

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#24]
By default the Phoenix ConnCase imports Ecto.Model. This can lead to ambiguous calls to `build`. I believe we may be able to solve this by using guards in our function. That ensure the first argument is an atom. 

From the Kernel.SpecialForms docs

### Ambiguous function/macro names

If two modules A and B are imported and they both contain a foo function with an arity of 1, an error is only emitted if an ambiguous call to foo/1 is actually made; that is, the errors are emitted lazily, not eagerly.

**Comment by henrik** [comment]
Afraid guards aren't enough. I think it must be different arities.

``` elixir
defmodule Lab do
  def build(x) when is_binary(x) do
  end
end

defmodule Fab do
  def build(x) when is_atom(x) do
  end
end

defmodule Run do
  import Lab
  import Fab

  def run do
    build("a")
  end
end

Run.run
```

**Comment by paulcsmith** [comment]
Oh yeah! You're very right. We decided to just add a note in the Readme instead. Hopefully that should do the trick! Thanks for taking a look though. I appreciate it :)
