### ISSUE TITLE
string_params_for with structs

### ISSUE THREAD

**Issue by Sitch** [thoughtbot/ex_machina#243]
I am using the money struct and i get enumerable errors when calling `string_params_for`

Error:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Money{amount: 1200000, currency: :USD}
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1767: Enum.reduce/3
    (ex_machina) lib/ex_machina/ecto.ex:321: anonymous fn/2 in ExMachina.Ecto.convert_atom_keys_to_strings/1
        (stdlib) lists.erl:1263: :lists.foldl/3
```

This is with master branch

**Comment by Sitch** [comment]
basically we just need to call: `Enumerable.impl_for(map)` before we traverse the map

**Comment by germsvel** [comment]
This should be fixed by https://github.com/thoughtbot/ex_machina/pull/245, so I will close it. Let me know if that's not the case, and we can reopen it.
