### ISSUE TITLE
Bug? - Building association via  params_with_assocs on module attributes blows up tests

### ISSUE THREAD

**Issue by digitalcake** [thoughtbot/ex_machina#254]
Say I have a phoenix app that generates an exunit test like so. 

```
defmodule MyApp.SomeController do
  ...
  @create_attrs %{ foo: "bar", some_relatation_id: 1 }
  ...
end
````

And say I want to use this style of tests so I naturally do. 

```
defmodule MyApp.SomethingController do
  ...
  @create_attrs params_with_assocs(:something)
  ...
end
````

I will end up causing the an issue with ecto 
```
(DBConnection.OwnershipError) cannot find ownership process for #PID<0.484.0>.
When using ownership, you must manage connections in one
of the four ways:
....

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:584: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:93: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.struct/7
...
```

Note:  if just using parms_for(:something) with module attributes there is no issue because ex_machina is not trying to handing building/creating the association outside of a method. 

I understand this is maybe not an issue with ex_machina but rather ecto, I felt it best posted here since I bet more are going to experience this issue as it relates to the workflow I've outlined.

**Comment by dbernheisel** [comment]
`params_with_assoc` involves database calls in order to create and get the relationships' IDs, which requires the Repo to be initialized and _used_, which doesn't happen at compile-time. I don't think it's a bug more than a difference between code in compile-time and run-time with Ecto.

**Comment by paulcsmith** [comment]
@digitalcake Thanks so much for posting. I hope someone comes to this and finds it useful. You are right that this is an Ecto configuration issue. It pops when the ownership is not set up properly.

Here is an article that may be helpful https://medium.com/@qertoip/making-sense-of-ecto-2-sql-sandbox-and-connection-ownership-modes-b45c5337c6b7

I'm sure there are others as well, but I hope this helps!
