### ISSUE TITLE
Documentation is incorrect

### ISSUE THREAD

**Issue by lsigauke** [thoughtbot/ex_machina#259]
I was looking at the documentation for `sequence/2` and it reads 
> Will generate "me-0@example.com" then "me-1@example.com", etc.

for this line `email: sequence(:email, &"me-#{&1}@foo.com")`

is this correct?

**Comment by germsvel** [comment]
Hi @lsigauke, that sentence seems correct to me. I may just not be seeing it though. Which part do you think is incorrect?

**Comment by lsigauke** [comment]
@germsvel should this not generate `me-0@foo.com` ?

**Comment by germsvel** [comment]
@lsigauke you're absolutely correct. I hadn't seen that! 

If you're up for it, could you open a PR to fix that?

**Comment by lsigauke** [comment]
@germsvel Yeah sure! :)

**Comment by germsvel** [comment]
Thanks again @lsigauke!
