### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by smt116** [thoughtbot/ex_machina#261]
Hi there,

thanks for doing a great job with providing this package! Is there any ETA for releasing a new version with the #227?

**Comment by germsvel** [comment]
Hi @smt116, thanks for asking when this will happen. We'll try to get a release out soon. I'll post back here when we do!

**Comment by germsvel** [comment]
@smt116 took longer than expected, but ex_machina 2.2.0 was released today. Please open an issue if you find anything amiss. Thanks!
