### ISSUE TITLE
ex_machina generators with phoenix

### ISSUE THREAD

**Issue by mikeni** [thoughtbot/ex_machina#262]
After spending a year of pain manually modifying test files after generating with phoenix, I finally decided to create some generators for phoenix, with optional support for ex_machina

https://github.com/mikeni/phoenix_custom_generators

Was wondering if someone could give feedback and if everything goes well, could we mention it in the readme?

**Comment by germsvel** [comment]
Hi @mikeni thanks for creating those custom generators with support for ex_machina. I don't use generators myself, so I'm unable to give feedback. Is this something that might get more traction in https://elixirforum.com/?

**Comment by germsvel** [comment]
@mikeni I'll close this for now since I don't have any feedback on generators, but please let me know if you wanted this open!
