### ISSUE TITLE
Sequence documentation conflicting with examples in README

### ISSUE THREAD

**Issue by itsdeezy** [thoughtbot/ex_machina#274]
## Readme Example
```
  def user_factory do
    %MyApp.User{
      name: "Jane Smith",
      email: sequence(:email, &"email-#{&1}@example.com"),
      role: sequence(:role, ["admin", "user", "other"]),                << This line
    }
  end
```

## Docs for sequence/2
```
sequence(name, formatter) View Source
sequence(any, (integer -> any)) :: any
```

## Also weird
`ExMachina.Sequence.next/2` supports [lists as 2nd param](https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina/sequence.ex#L62)

But `ExMachina.sequence/2` **ONLY** supports a formatter function as 2nd param.

Would like to use this for enums, anyone have a temp solution?

**Comment by itsdeezy** [comment]
Did some digging, looks like the last release was in august, which did not include the merge [here](https://github.com/thoughtbot/ex_machina/pull/227/files#diff-9ae4e2a1820bb04c6124044fa529976a). Use master boys!

**Comment by germsvel** [comment]
@itsdeezy there was a release today that should include support for using lists in sequences.
