### ISSUE TITLE
Suggestion: build_chain and insert_chain

### ISSUE THREAD

**Issue by wmnnd** [thoughtbot/ex_machina#290]
Hey there,

I’ve been enjoying using `ex_machina` quite a lot. Thank you for this neat little application!

There is one thing I have come across in several projects that used `ex_machina`: It would be convenient if there was a way to build/insert a chain of records that depend on each other.

Here is my suggestion for `build_chain/1` and `insert_chain/1`.

`build_chain/1` takes a list as its only argument.

In its simplest form `build_chain([:user, :project, :task])` would then execute the following:
1. `build(:user)`
2. `build(:project, %{user_id: "$USER_ID")`
3. `build(:task, %{user_id: "%USER_ID", project_id: "$PROJECT_ID"}})`

Additional parameters can be provided to `build_chain/1` using tuples: `build_chain([{:user, %{email: "mail@example.org"}}, :project])` would do this:
1. `build(:user, %{email: "mail@example.org"})`
2. `build(:project, %{user_id: "$USER_ID")`

For really complicated cases, a three-element tuple can be used to use custom foreign keys:
 `build_chain([{user}, {:project, %{}, [user: :owner_id]}])` would build the following structs:
1. `build(:user)`
2. `build(:project, %{owner_id: "$USER_ID")`

Finally, shared associations can be provided to `build_chain/2` and `insert_chain/2`:
`build_chain([:project, task], user: %User{id: "foo"})` will do this:
1. `build(:project, %{user_id: "foo"})`
2. `build(:task, %{user_id "foo")`

I’m looking forward to your feedback on this idea and would be happy to provide a PR.

**Comment by germsvel** [comment]
Hi @wmnnd, thanks for the suggestion! From my use of `ex_machina`, I am not quite sure when I would use something like `build_chain`. In the examples you suggest, I know it's a little more typing to do this, 

```elixir
user = build(:user)
project = build(:project, user: user)
build(:task, project: project, user: user)
```
but I think I would prefer the explicitness over something like 

```elixir
build_chain(:user, :project, :task)
```

Would the latter mean `task` uses both `project` and `user`? What if `task` only uses `user`? I think it would be more confusing. 

That being said, if you find that you're always using all those three together, there's no reason why you couldn't define a factory that does all of that underneath for you, 

```elixir
def task_with_project_and_user_factory
  user = build(:user)
  project = build(:project, user: user)
  %Task{project: project, user: user}
end
```

What do you think? Am I missing something important about your suggestion?

**Comment by wmnnd** [comment]
My use-case is that it allows for easy automation of tests for schemas that share certain properties.

You can simply define something like `@chain [:user, :project]` for your `Task` module and use that information to auto-generate tests shared among schema modules.

In your example (`build_chain(:user, :project, :task)`), `task` would indeed use both `project` and `user`.
If `task` uses only `user`, you wouldn’t need to create `project` as part of the chain. If you really wanted to create `project` anyways and not use it for `task`, you could use the tuple-syntax I described in my first post.

**Comment by germsvel** [comment]
Hi @wmnnd, I'm not convinced that the benefits of something like `build_chain` would outweigh the complexity that it would introduce into ex_machina. If we were to do something like this, I think it would have to have a nice api so that it's clear how to work it, and so that people aren't confused with it.  

The nice thing about ex_machina, however, is that it's just functions and structs. So I think you could create the `build_chain` function on your own to test it out and see how well it performs for you. If you find a nice api for it and if others find it useful, maybe it could make sense to try to introduce it. 

I think something like this could work, 

```elixir
# in your Factory.ex file
def build_chain(factories) do 
  Enum.readuce(factories, [], fn factory_atom, built_factories -> 
    {factory_atom, build(factory_atom, built_factories)}
  end)
end

# in tests
{:task, task} = build_chain([:user, :project, :task])
```

I'll close this for now, but let me know if you'd like to revisit this at some point.
