### ISSUE TITLE
[Question] Is it possible to not load associations after insertion?

### ISSUE THREAD

**Issue by samidarko** [thoughtbot/ex_machina#295]
I'm saving some records to the database using ExMachina `insert(:comment)` but my assertions are wrong because ExMachina always load relations and it's not the case when I'm fetching with Ecto and not calling `Repo.preload`.

Let's say I have 2 factories `comment` and `user`:

```ruby
def user_factory do
  %User{
    name: "some name"
  }
end

def comment_factory do
  %Comment{
    content: "some content",
    user: build(:user)
  }
end
```

when I'm testing

```ruby
  test "should retrieve last comment" do
    comment = fixture(:comment)
    assert Comment.get_last_comment() == comment
  end
```

Assertion if failing because on the left I have
```ruby
%Comment{
    ...,
    content: "some content",
    user: #Ecto.Association.NotLoaded<association :user is not loaded>
}
```
and on the right
```ruby
%Comment{
    ...,
    content: "some content",
    user: %User{ name: "some name" }
}
```
I'm trying to avoid:
 - using `Repo.preload` on my left records because sometimes there are quite a lot of dependencies
 - testing each property individually

Thanks by advance for your help

**Comment by samidarko** [comment]
I asked the question on SO [here](https://stackoverflow.com/questions/51815919/is-it-possible-to-not-load-associations-after-insertion-with-exmachina) and solved it with answer [there](https://stackoverflow.com/questions/49996642/ecto-remove-preload/49997873#49997873).

Nonetheless, would it be a good to have in the library itself or should we handle it the way suggested  ?

**Comment by germsvel** [comment]
Hi @samidarko, I'm not quite sure I follow your question here. It seems to me that if you're using `insert(:comment)` and comment has the following factory defined, 

```elixir
def comment_factory do
  %Comment{
    content: "some content",
    user: build(:user)
  }
end
```
 
then the `insert` function is correct in inserting the user and the comment, and then returning the comment with the user included. I think it would be _more_ confusing and unexpected if you did `build(:comment)` and it did not include the user (since it's defined in the factory). `insert` just extends that functionality by inserting those records into the database. 

An alternative to your test might be simply checking the `comment.id` or something of that nature. Would something like that solve your situation?

**Comment by zimt28** [comment]
I‘ve now built a `remove_field/2` helper, which works on maps and structs, but it would still be nice to have a "native" solution.

**Comment by samidarko** [comment]
Ecto doesn't load the relations by default. Let's say I have a comment in my db with id 1, I would do:

```elixir
Repo.get!(Comment, 1)
```
and the result would be:

```elixir
%Comment{
    content: "some content",
    user: #Ecto.Association.NotLoaded<association :user is not loaded>
}
```

If I wanted to load the relations I would do:
```elixir
Repo.get!(Comment, 1) |> Repo.preload(:user)
```

When I user `insert(:comment)` everything is already loaded. It would be nice it we could have an option to get the same behavior than Ecto.

Anyway we worked around the problem as followed:

We added to **Repo** the following function:

```elixir
  def forget(_, _, cardinality \\ :one)

  def forget(struct, fields, cardinality) when is_list(fields),
    do:
      fields
      |> Enum.reduce(struct, fn field, acc ->
        forget(acc, field, cardinality)
      end)

  def forget(struct, field, cardinality) do
    %{
      struct
      | field => %Ecto.Association.NotLoaded{
          __field__: field,
          __owner__: struct.__struct__,
          __cardinality__: cardinality
        }
    }
  end
```
and we do:
```elixir
insert(:comment) |> Repo.forget(:user)
```

I understand what you are saying @germsvel when you say to just test `id` but we prefer to have a more comprehensive approach like:

```elixir
comment = insert(:comment)
assert list_comments() == [comment]
```

**Comment by germsvel** [comment]
Thanks for that clarification @samidarko. 

You're totally correct that `Repo.get!(Comment, 1)` would result in something like this:

```elixir
%Comment{
    content: "some content",
    user: #Ecto.Association.NotLoaded<association :user is not loaded>
}
```

I think that the confusion is coming from the fact that `insert` returns a value. It returns a value but it is not acting like a `Repo.get!`. Rather ex_machina's `insert` just uses Ecto's [insert!/2](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert!/2). So if you were to do the following, 

```elixir
comment = %Comment{
  content: "some content",
  user: %User {
    name: "some name"
  }
}

result = Repo.insert!(comment)
```

the `result` would have the user in there. It's not "loaded" in the sense that we're preloading associations or something like that. It's just that if you insert a series of nested structs with `Ecto`, it will return those. Does that make sense? 

As for testing, you could also modify your factory to not have the `user` built into it, 

```elixir
def comment_factory
  %Comment{ content: "some content"}
end

def with_user(%Comment{} = comment) do
  user = build(:user) 
  struct!(comment, %{user: user})
end
```

Then, in the places where you don't want the user, you can just call `insert(:comment)`, and if you need the user, you can do something like `build(:comment) |> with_user() |> insert()`

Not sure how useful that is in your case (if a comment must always have a user, then maybe it needs to be there), but just trying to think of alternatives.

**Comment by samidarko** [comment]
It's clearer for us to understand ExMachina approach since you mentioned that it's closer from [insert!/2](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert!/2) than [get/3](https://hexdocs.pm/ecto/Ecto.Repo.html#c:get/3).

We are going to keep using our `forget` function for the purpose because it's closer from what we want to get than compose the way you described, still useful technique in other use cases.

Thanks for your time @germsvel and for the work done on this very useful library. I think we can close this issue.

**Comment by c4710n** [comment]
Enhanced version of example provided by samidarko: 
+ https://gist.github.com/c4710n/7f472167c78750126d173fde1389e616

**Comment by c4710n** [comment]
> Enhanced version of example provided by samidarko:
> 
> * https://gist.github.com/c4710n/7f472167c78750126d173fde1389e616

I contributed this feature to Ecto - [Ecto.reset_fields/2](https://github.com/elixir-ecto/ecto/commit/d3bcf87330f70632c9ea947a436d495eef0dd32a).

And it will be included in next release.
