### ISSUE TITLE
Missing @spec for list sequences

### ISSUE THREAD

**Issue by eteubert** [thoughtbot/ex_machina#296]
According to documentation these are allowed sequences (and they do work):

```elixir
sequence(:foo, [true, false])
sequence(:bar, ["a", "b"])
```

However, Dialyzer complains about them breaking the contract.

> The call 'Elixir.ExMachina':sequence('foo',[boolean(),...]) breaks the contract (any(),fun((integer()) -> any())) -> any()

**Comment by barthez** [comment]
Your issue was solved in https://github.com/thoughtbot/ex_machina/pull/278. It is not yet released, though.

**Comment by germsvel** [comment]
Hi @eteubert, I just released a small version bump that includes this in there. I'll close this for now, but let me know if you're still running into that issue.
