### ISSUE TITLE
Question: How can I customize a factory using struct?

### ISSUE THREAD

**Issue by thiagogsr** [thoughtbot/ex_machina#302]
Hi

I would like to send attributes to an factory like the [example](https://github.com/thoughtbot/ex_machina#overview) in README

```elixir
# derived factory
  def featured_article_factory do
    struct!(
      article_factory(),
      %{
        featured: true,
      }
    )
  end
```

```elixir
insert(:featured_article, author: user)
```

Is it possible? It is not working for me

**Comment by germsvel** [comment]
Hi @thiagogsr, I'm not quite sure what your `article_factory` has for it's attributes or relationships. But assuming it has an author, that should work. 

Could you include a little more context onto what's going on? What does your `article_factory` have in it, what does your article schema look like, and what are you getting when you do `insert(:featured_article, author: user)`?

**Comment by thiagogsr** [comment]
@germsvel in my case, the factories are:

```elixir
def user_factory do
  %Accounts.User{
    name: "Full name",
    email: sequence(:email, &"email-#{&1}@example.com"),
    username: sequence(:username, &"username#{&1}"),
    password_hash: Bcrypt.hashpwsalt("secret"),
    packages: [insert(:package)]
  }
end

def licenced_user_factory do
  user = user_factory()
  struct!(user, %{licences: [build(:licence, package: List.first(user.packages))]})
end
```

I'm creating an user with packages and licences, but I need to use the same package for user and licence, therefore I'm inserting the package instead of building, since if I use `build`, it will create the package twice.

When I call

```elixir
package = insert(:package)
insert(:licenced_user, packages: [package])
```

It didn't use the package created before the `licenced_user`, the factory creates a new one.

**Comment by germsvel** [comment]
Thanks for providing that context! I think I see the problem. Suppose your package has a `name` attribute (just so I can distinguish them here). Let's say you do the following, 

```elixir
# in factory definitions
def user_factory do
  %Accounts.User{
    name: "Full name",
    email: sequence(:email, &"email-#{&1}@example.com"),
    username: sequence(:username, &"username#{&1}"),
    password_hash: Bcrypt.hashpwsalt("secret"),
    packages: [insert(:package, name: "package_b")]  # <- note package b here
  }
end

def licenced_user_factory do
  user = user_factory()
  struct!(user, %{licences: [build(:licence, package: List.first(user.packages))]})
end

# in tests
package_a = insert(:package, name: "package-a") # <- note package a here
insert(:licenced_user, packages: [package_a])
```

When you do the `insert(:licenced_user, packages: [package_a])`, it'll generate everything in your `licensed_user_factory` and replace the value for `packages` with the `[package_a]` that you're passing in. But this is the thing, it _already_ inserted the package with name `"package_b"`, and it used that for the licenses. 

In other words, this is what you're generating, 

```elixir
%Accounts.User{
  name: "Full name",
  emails: "email-1@example.com", 
  username: "username1",
  password_hash: "somethinghash",
  packages: [%Package{name: "package_a"}]
  licences: %License{ package: %Package{name: "package_b"} }
}
```

There's not a lot of magic in `ex_machina`. It'll simply build/insert what is defined in the `thing_factory` definition. If you pass an attribute, it'll override that attribute, but not any other attributes that are dependent on it. Does that make sense? 

As for your test setup, I think you can accomplish what you're looking for by changing your `licenced_user_factory` to something like this,

```elixir
def licenced_user_factory do
  package = insert(:package)
  license = build(:license, package: package)
  user = build(:user, packages: [package], licenses: [license])
end
```

Would that work?

**Comment by thiagogsr** [comment]
Thanks for the detailed explanation @germsvel. I understood your point.

The challenge is create a new package with specific attributes for some tests, and use the same for user and license. For these cases I will create the package and the licence in the test and use your suggestion for the most of cases.

Thank you
