### ISSUE TITLE
undefined function insert_list/2

### ISSUE THREAD

**Issue by yordis** [thoughtbot/ex_machina#305]
I am not sure why my package stop working.

I keep getting this issue.

```bash
== Compilation error in file test/straw_hat_map/locations_test.exs ==
** (CompileError) test/straw_hat_map/locations_test.exs:6: undefined function insert_list/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
make: *** [testing] Error 1
```

On this line https://github.com/straw-hat-team/straw_hat_map/blob/ba92edd03054de3ef278988c6a0b4b8b247be4b1/test/straw_hat_map/locations_test.exs#L6

The factory is being imported here https://github.com/straw-hat-team/straw_hat_map/blob/ba92edd03054de3ef278988c6a0b4b8b247be4b1/test/support/data_case.ex#L12

**Comment by germsvel** [comment]
Hi @yordis, that's very strange. Any more info you have into that? What version of ex_machina are you using?

**Comment by germsvel** [comment]
Thanks for sending the `mix.lock` file. I think I may be the version you're using. Version `0.6.2` is fairly old, and I believe `insert_list` used to be called `create_list`. I would recommend updating to a newer version, but if you want to stay with an older version, try `create_list`. I believe that should work.

**Comment by yordis** [comment]
I forced my setup to the latest version and it works, sorry for such of a dumb mistake,  I never expected Hex to be installing an old version and trusted blindly.

My apologies.

**Comment by germsvel** [comment]
Not a problem @yordis. Glad we got it resolved. 👍
