### ISSUE TITLE
ExMachina not inserting timestamps properly in Ecto 3.0

### ISSUE THREAD

**Issue by mbramson** [thoughtbot/ex_machina#323]
Noticed this while upgrading a project to Ecto 3.0. This project is using Postgres.

If I define an ecto schema using usec timestamps like so:

```
defmodule Thing do
  schema "things" do
    field :attribute, :string

    timestamps(type: :naive_datetime_usec)
  end
end
```

and then define a factory like so:

```
defmodule Factory do
  use ExMachina.Ecto, repo: Repo

  def thing_factory do
    %Thing{
      attribute: "doesnt matter"
    }
  end
end
```

The `inserted_at` values do not behave as I would expect.

```
iex> thing = Factory.insert(:thing)
...
iex> thing.inserted_at
~N[2018-12-28 04:12:48.284042]
iex> Repo.get!(Thing, thing.id).inserted_at
~N[2018-12-28 04:12:48.000000]
```

So it appears that although the struct itself returns a very precise value, only the second precision is actually persisted to the database.

This matters to me because I care about the precise value of that timestamp, and want to assert that the value in the struct is present in some data structure which includes this timestamp. There are some hacky ways I can get around this, but really I just think that these shouldn't be necessary. Seems like a pretty central property of `ExMachina` that it should save the exact values to the database which are actually returned by `insert/1` function.

**Comment by germsvel** [comment]
Hi @mbramson, that's odd behavior. ExMachina is just using ecto underneath. 

Do you know if you also changed the migration timestamp to `:naive_datetime_usec`? You can do it at the [repo level](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-repo-configuration) or at each migration when declaring [timestamps()](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#timestamps/1). 

See also the _Calendar Types_ section on http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/

If that doesn't fix it, let me know, and we can see what else might be causing the issue. We might need to create a sample app to reproduce the error.

**Comment by mbramson** [comment]
@germsvel, so these migrations work fine in development. I can actually save microsecond resolution without issue and observe those saved values in the application with microsecond resolution. It's only in test using ExMachina factories where I've observed this issue. Taking a peak at the relevant tables in the dev and test environment, they have identical datatypes. Additionally, per [Postgres timestamp docs](https://www.postgresql.org/docs/9.6/datatype-datetime.html), there's no such thing as specifying microsecond resolution in a migration as all timestamps have microsecond resolution at the database level.

Since ecto_sql made the default timestamps have second resolution and forced you to specify the microsecond type specifically, my guess is that when upgrading that ExMachina dependency to Ecto 3.0, there's something within ExMachina that just uses the default timestamps.

**Comment by mbramson** [comment]
Just verified that by changing nothing in the database, and simply inserting my records manually with a changeset and my `Repo` module, my tests now pass, since the timestamps have microsecond resolution.

**Comment by mbramson** [comment]
And... that test only passed because the line shifted :). You are correct, adjusting the timestamps in the migrations themselves does fix this issue.

**Comment by germsvel** [comment]
Glad to hear that worked!
