### ISSUE TITLE
Use do_build/2 and do_create/2 internally so that you can have custom build/create functions

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#35]
I was thinking about a way to do things after/before create/build or to do intersting things with the attrs if needed. I think it would be awesome to be able to define a custom function like so

```elixir
def create(:article, attrs \\ []) do
  do_create(:article, attrs) |> with_comment
end

def build(:user, attrs \\ []) do
  email = attrs.first_name <> attrs.last_name <> "@foo.com"
  do_build(:user, Map.put_new(attrs, email: email)) 
end
```

`do_build` and `do_create` would do what `create/2` and `build/2` do today, and `create/build` would just call `do_create` and `do_build` with the passed in arguments. This would be an easier change and would allow for a very flexible build/create process

**Comment by paulcsmith** [comment]
I'm open to other thoughts proposals on how to handle this though. I personally like this because it's super simple to implement and it keeps the build/create changes separate without cluttering up the main factory definition.

**Comment by jsteiner** [comment]
We discussed this in person today, but I wanted to document my concern that this splits the factory definition into two places, so it's easier to miss that you're assigning the comment if you only look at the `factory` block. This may not actually matter. I need some more time to think about it, but I probably won't have time until next Friday.

**Comment by paulcsmith** [comment]
Thanks for documenting that, Josh. I don't know how confusing it would be though if it's defined right underneath the factory? I definitely can see it being confusing if it's defined underneath somewhere though. Maybe we can think of something better on Friday though

**Comment by josevalim** [comment]
I don't like this approach, honestly. Because the function is called `do_build`, it feels like an implementation detail. @jsteiner also brought valid concerns of splitting the factory definitions apart. Why do we need this? Why this cannot be done in the factory definition itself?

**Comment by paulcsmith** [comment]
@josevalim I mostly liked overriding `build/create` because it requires very few changes to the code and seemed simple in my mind. You can do things before/after build or create without learning any new functions. Just override build/create and do whatever you need to do. 

We could do it in the factory definition though, but would require a few more functions and changing how `build` and `create` work. 

```
%Article{
  title: "My Article"
} 
|> after_create(&add_comment)

# Returns a struct like
%ExMachina.Factory{
  record: %User{title: "MyArticle"},
  before_create_functions: [],
  after_create_functions: [&add_comment]
}
```

Then the `build` and `create` functions would look for `ExMachina.Factory` struct and could apply the functions at the appropriate time. This could definitely be done, but I don't like it that much for some reason. To me it clutters up the factory and I'd rather split it up into a different function :S Maybe that's just me though :S

**Comment by paulcsmith** [comment]
I think we'll go a different direction for this
