### ISSUE TITLE
ex_machina + stream_data

### ISSUE THREAD

**Issue by ibarchenkov** [thoughtbot/ex_machina#351]
Hello ex_machina maintainers.

I've discovered that data for Ecto factories could be generated using [StreamData](https://hexdocs.pm/stream_data/StreamData.html) library. Here's [an example](https://gist.github.com/ibarchenkov/b5982e42e660fe33eb023c164b1424d3). The most compelling thing to me in this approach is that I can define one set of functions and use them simultaneously as Ecto factories in unit/controller tests **and** as generators in property-based testing.
I have a working solution and almost ready to share it with the community.
Please, consider the following questions:
* Do you want me to contribute such functionality to your project?
* If not, do you mind if I borrow some code in `params_for*` functions?

Thank you.

**Comment by germsvel** [comment]
Hi @ibarchenkov, thanks for reaching out! I haven't had the chance to use `StreamData` yet, but property-based testing is something near the top of my list to devote some time into. Given that I'm not familiar with that, I'm not sure I can judge whether what you're talking about would be a good addition to `ExMachina` or not. So unfortunately I don't think contributing that functionality to the project would be a good idea yet before I can give that some more serious research and thinking. 

To your other question, 

> If not, do you mind if I borrow some code in params_for* functions?

Absolutely don't mind! If you find something useful in the codebase, feel free to copy it. 

And maybe once I get more well versed with property-based testing and `StreamData`, I'll come back here and ask you how it's going! 

Either way, thank you for reaching out and asking!

**Comment by Munksgaard** [comment]
I know it's been a while, but I'm curious about whether this issue has been given any thought? I would love to start using ex_machina, but at the same time I want to keep my stream generators. I feel like the two would be a natural marriage, but I'm likely overlooking some deeper complexity.

Any thoughts?

**Comment by Munksgaard** [comment]
I've tried my hand at a PR here: #497
