### ISSUE TITLE
"Factory is not loaded and could not be found" when trying to use through `mix run priv/repo/seeds.exs`

### ISSUE THREAD

**Issue by edwinthinks** [thoughtbot/ex_machina#353]
Hey there,

I've believe that I have installed `ex_machina` properly for all my environments and would like to use this in seeding my local/dev database. However, I am running into an issue were the factory appears not be loading in my `MIX_ENV=dev` environment.

In my `priv/repo/seeds.exs` file:
```
import YouMustGoto.Factory

user = insert(:user)
```
When I do `mix run priv/repo/seeds.exs` I get the following error:
```
** (CompileError) priv/repo/seeds.exs:13: module YouMustGoto.Factory is not loaded and could not be found
    (elixir) lib/code.ex:767: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:147: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:86: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```
Interestingly enough when I do `MIX_ENV=test mix run priv/repo/seeds.exs`, I do not get the error and appears to work fine.

I'am using elixir `1.8.0` and here is how I installed ex_machina in my deps:
```
      {:ex_machina, "~> 2.3"},
```

Wondering what I could be doing wrong here. Thanks for help in advance!

**Comment by thiamsantos** [comment]
@edwinthinks Where your factory is located? It is inside your the `test` folder? If yes, it may be the cause of you not been able to use your factory with `MIX_ENV=dev`.

Normally we have the following lines in our `mix.exs`, with that we are telling the compiler to load the folder `test/support` during compilation. But that happens only with `MIX_ENV=test`, for the other environments, only the `lib` folder will be included. Meaning that a factory defined inside `test/support` will not be available on `dev` environment.

```elixir
# mix.exs

defp elixirc_paths(:test), do: ["lib", "test/support"]
defp elixirc_paths(_), do: ["lib"]
```

**Comment by edwinthinks** [comment]
@thiamsantos ahh that makes total sense! Thanks @thiamsantos I had to update my paths to include the factories to make this happen :).

Thanks closing!

**Comment by sergiotapia** [comment]
Would be Googlers who find this thread. The solution here was correct, however keep in mind in a Docker environment, say a Dockerfile **don't forget to copy your test folder!** Otherwise the module will not "exist" during compilation and you'll get this error despite setting your elixirc_paths properly!

I had to do this for mine to work:

```
# copy assets and heex templates for postcss
# to detect css classes and add them to css
# final payload file.
COPY priv priv
COPY assets assets
COPY lib lib
COPY test test
```
