### ISSUE TITLE
ExMachina doesn't work with embeds

### ISSUE THREAD

**Issue by jsteiner** [thoughtbot/ex_machina#37]
Embeds can only be manipulated via changesets, be it on insert, update or delete.

**Comment by paulcsmith** [comment]
This should be covered by https://github.com/thoughtbot/ex_machina/commit/080498ee4c3a5a70b69f478c7877d2979e879e01 but we it might be good to add some tests around embeds just to make sure

**Comment by iancanderson** [comment]
I'll take a stab at this test

**Comment by paulcsmith** [comment]
@iancanderson Thanks! Be sure to branch from 0.4.0 or it will be quite difficult to get the test passing :)

**Comment by iancanderson** [comment]
Closing since this is done and tested
