### ISSUE TITLE
[Question] how to generate the email based on the user's name?

### ISSUE THREAD

**Issue by thojanssens** [thoughtbot/ex_machina#372]
Hello 👋

How do I generate the email based on a given name?

```
user1 = insert(:user, %{name: "John", email: "john@example.com", role: role_admin})
user2 = insert(:user, %{name: "James", email: "james@example.com", role: role_guest})
```

I would like to avoid typing `<name>@example.com` above ^ and write just like that with generated email:
`user1 = insert(:user, %{name: "John", role: role_admin})`

Thank you for any help!

**Comment by germsvel** [comment]
@thojanssens I'm going to close this issue. I think @dbernheisel's answer is what I would suggest. Let me know if you still run into problems, and we can reopen this if needed.
