### ISSUE TITLE
def build/2 defines defaults multiple times

### ISSUE THREAD

**Issue by bmfay** [thoughtbot/ex_machina#392]
I am on a brand new project (Elixir 1.7.4) trying to use ex_machina (2.4.0).  When following the example in the README, I get a compile error at line 7 when using ExMachina

```   use ExMachina ```

When attempting compilation, I get the following error:

```
** (CompileError) test/support/factory.ex:7: def build/2 defines defaults multiple times. Elixir allows defaults to be declared once per definition. Instead of:

    def foo(:first_clause, b \\ :default) do ... end
    def foo(:second_clause, b \\ :default) do ... end

one should write:

    def foo(a, b \\ :default)
    def foo(:first_clause, b) do ... end
    def foo(:second_clause, b) do ... end

    test/support/factory.ex:7: (module)
```

I looked at the source here (https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina.ex) but don't see it violating this.  I must be missing something here...

**Comment by germsvel** [comment]
👋  Hi @bmfay, can you include a copy of the factories you're defining and the test you're trying to write? Any code to help me reproduce the error would be most helpful!

**Comment by bmfay** [comment]
@germsvel thanks for quick response.  I realized that I had

```
defmodule X.Factory do
  # with Ecto
  use ExMachina.Ecto, repo: X.Repo
  use X, :shared

  # without Ecto
  use ExMachina
```

And just spaced out on not noticing that you must pick one or the other, in my case removing use ExMachina.
