### ISSUE TITLE
Compiler warning when using an a project using Elixir 1.11

### ISSUE THREAD

**Issue by bowmanmike** [thoughtbot/ex_machina#398]
Running `mix compile` in a project using Elixir 1.11 causes a compiler error which originates in `ex_machina`. The `ExMachina.Strategy.__using__` macro has a function call without parentheses. The trouble is that even when running `mix compile --warnings-as-errors --no-deps-check`, the compilation still fails. I assume this is because the `use ExMachina.Strategy` call compiles that function into our own code, so the compiler thinks that error is coming from our code, rather than a library.

_Edit_ screenshot
![Screen Shot 2020-10-19 at 2 18 54 PM](https://user-images.githubusercontent.com/15827207/96495902-88e19e00-1216-11eb-935d-f5c8dcee1d7c.png)

**Comment by germsvel** [comment]
Thanks for opening this issue @bowmanmike! If you're up for it, I'd love a PR for this. Otherwise, I'll try to get to Elixir 1.11 warnings and issues sometime this or next week.

**Comment by bowmanmike** [comment]
Thanks for the quick reply @germsvel! I'll see if I can get to it sometime this week.

**Comment by crbelaus** [comment]
I've experienced this problem myself so I've created a merge request to fix it.
