### ISSUE TITLE
Allow sequence in attributes passed to `insert_list`

### ISSUE THREAD

**Issue by kevinkirkup** [thoughtbot/ex_machina#415]
I'd like to be able to generate a list instances that have a custom parameters sequence, but this doesn't appear to work.

```ex
myList = insert_list(8, :myFactory, name: sequence(:name, &"Custom-Name-#{&1}"))
```

instead I'm getting a compile error:

```
** (exit) exited in: GenServer.call(ExMachina.Sequence, {:get_and_update, #Function<2.66728067/1 in ExMachina.Sequence.next/3>}, 5000)
    ** (EXIT) an exception was raised:
        ** (BadFunctionError) expected a function, got: "Custom-Name-"
           (ex_machina 2.7.0) lib/ex_machina/sequence.ex:125: anonymous fn/4 in ExMachina.Sequence.next/3
           (elixir 1.11.3) lib/agent/server.ex:16: Agent.Server.handle_call/3
           (stdlib 3.14) gen_server.erl:715: :gen_server.try_handle_call/4
           (stdlib 3.14) gen_server.erl:744: :gen_server.handle_msg/6
           (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Any ideas?

**Comment by germsvel** [comment]
Hi @kevinkirkup, do you have any more information you can provide? Can you share your factory setup and your test setup? 

Just looking at the error, it seems like for some reason, it doesn't get that the second argument to `sequence/2` is a function: 

> ** (BadFunctionError) expected a function, got: "Custom-Name-"

But `name: sequence(:name, &"Custom-Name-#{&1}")` should be a valid sequence. I tested that in the ExMachina tests and it works. 

Usually, I'd use sequences in the factory definition, not when calling `insert`. Are you calling the `insert_list/3` function in a test or inside the factory? Do you get a different result if you try inside the factory?

**Comment by kevinkirkup** [comment]
Hi @germsvel, here is the factory definition:
```
  def myFactory_factory(attrs) do
    %MyFactory{
      name: sequence("Test-MyFactory"),
    }
    |> merge_attributes(attrs)
  end
```

**Comment by kevinkirkup** [comment]
I updated the factory and now I'm seeing a different behavior.

Changed the factory to:
```
  def myFactory_factory(attrs) do
    name = Map.get(attrs, :name, sequence("Test-MyFactory"))
    %MyFactory{
      name: name,
    }
    |> merge_attributes(attrs)
  end
```

```
     test/xxx_web/controllers/myfactory_controller_test.exs:42
     ** (Ecto.ConstraintError) constraint error when attempting to insert struct:

         * myfactory_id_name_index (unique_constraint)

     If you would like to stop this constraint violation from raising an
     exception and instead add it as an error to your changeset, please
     call `unique_constraint/3` on your changeset with the constraint
     `:name` as an option.

     The changeset has not defined any constraint.
```

**Comment by germsvel** [comment]
@kevinkirkup for the last error (the unique constraint one) are you passing a sequence when calling `insert`? 

In other words, are you still calling this in your test? 

```elixir
myList = insert_list(8, :myFactory, name: sequence(:name, &"Custom-Name-#{&1}"))
```

If so, the error is happening because you're generating the sequence first, and then passing that generated value into `insert_list/3`, which means all 8 of your records have the same `name`. In other words, this is the equivalent of what you're doing: 

```elixir
# generates a name
name = sequence(:name, &"Custom-Name-#{&1}")
# e.g. => "Custom-Name-1"

# passes that name to all 8 factories
myList = insert_list(8, :myFactory, name: name)
```

In order to get around that you can [delay the evaluation](https://hexdocs.pm/ex_machina/readme.html#delayed-evaluation-of-attributes) of attributes by passing a function: 

```elixir
myList = insert_list(8, :myFactory, name: fn -> sequence(:name, &"Custom-Name-#{&1}") end)
```

All in all, I'd expect the code to look something like this: 

```elixir
# factory.ex
def myFactory_factory(attrs) do
    %MyFactory{
     # the default sequence
      name: sequence("some name")
    }
end

# some_test.exs
test "I can do something" do
  # overriding the name attribute
  a = insert_list(8, :myFactory, name: fn -> sequence(:name, &"Custom-Name-#{&1}") end)
end
```

That should solve your unique constraint error.

**Comment by kevinkirkup** [comment]
ah, ok.
I was able to get everything working with this:
```
mythings =
  insert_list(mything_count, :mything,
    name: fn -> sequence(:name, &"Custom-Name-#{&1}") end
  )

def mything_factory(attrs) do
  name = Map.get(attrs, :name, sequence("Test-Thing"))

  %MyThing{
    name: name,
  }
  |> merge_attributes(attrs)
  |> evaluate_lazy_attributes()
end
```

Thanks for your help!
