### ISSUE TITLE
Hundreds of depreciation compiler warnings when running tests

### ISSUE THREAD

**Issue by tfantina** [thoughtbot/ex_machina#416]
Several months back I upgraded a project from Elixir 1.8 to 1.10.4 and from Phoenix 1.3.0 to 1.4.17 since then whenever I run the test suite I get hundreds of warnings (to the point where the test suite is nearly indecipherable): 
```
warning: passing float to Decimal.new/1 is deprecated as floats have inherent inaccuracy. Use Decimal.from_float/1 or Decimal.cast/1 instead
  (decimal 1.9.0) lib/decimal.ex:1187: Decimal.new/1
  (ecto 2.2.12) lib/ecto/type.ex:587: Ecto.Type.cast/2
  (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:72: ExMachina.EctoStrategy.cast_value/3
  (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:58: anonymous fn/2 in ExMachina.EctoStrategy.cast_all_fields/1
  (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:49: ExMachina.EctoStrategy.cast/1
  (ex_machina 2.7.0) lib/ex_machina/ecto_strategy.ex:25: ExMachina.EctoStrategy.handle_insert/2
```

I'm not sure if this is an ExMachina issue or not it's just the first external library in the call-stack, if it's unrelated please feel free to just close this issue. Also I know this is not likely actually an issue with ExMachina but something in my setup, I'm posting hoping someone will have encountered this, or have some insights.

Thank you.

**Comment by tfantina** [comment]
Ah, I solved it by upgrading `phoenix_ecto` from `3.0` to `3.6.0`.

**Comment by axelson** [comment]
Doesn't that just mean there's only one instance of the warning instead of many? If so it would still be good to get that fixed in ex_machina.

**Comment by germsvel** [comment]
Hi @axelson @tfantina thanks for bringing this up. 

I'm not sure there's anything we can do from ExMachina's side to deal with this. ExMachina calls Ecto's casting functions [here](https://github.com/thoughtbot/ex_machina/blob/9f92dec163732af13c67ccbef5f71f892ad70d32/lib/ex_machina/ecto_strategy.ex#L72), so I believe this is a matter of upgrading Ecto (or `phoenix_ecto` like Travis did) to a version that uses `Decimal.from_float` or `Decimal.cast`. At least that's what I'm gathering from that backtrace. If you see something that could be changed, I'd be happy to review a PR.

**Comment by tfantina** [comment]
@germsvel I think you are right, although after running ` rm -rf deps` I realized that I may not have actually solved the problem just yet but it seems to still be originating with Ecto.  I'll update this issue accordingly.  I'm still assuming it's an Ecto thing but if it turns out to be ExMachina I open up a PR.
