### ISSUE TITLE
insert/2 doesn't work with compound primary keys

### ISSUE THREAD

**Issue by joeljuca** [thoughtbot/ex_machina#417]
Hello!

First of all, thank you for writing and sharing ExMachina. Super useful! I'm using it to generate entries during tests, and today I got an error for a new Ecto schema I'm writing:

```
** (Postgrex.Error) ERROR 42703 (undefined_column) column "id" does not exist

debug] QUERY ERROR db=0.0ms queue=14.7ms idle=1342.2ms
INSERT INTO "matches" ("user_id","session_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" [2, 1, ~U[2021-05-05 17:27:41Z], ~U[2021-05-05 17:27:41Z]]
```

My table does not have an `id` field, the primary key is a compound one (session_id and user_id fields). So, the `RETURNING "id"` part of the generated SQL query is breaking the functionality.

Any idea of how I could solve/overcome/avoid this issue?

**Comment by joeljuca** [comment]
For those reading this issue from your mail reader, I'm sorry! I accidentally created the issue before filling it with the needed information. It should look good now (the issue is with `insert/2` not playing well with tables that lack an `id` field, using a compound primary key - a combination of two columns as a unique ID, instead of a dedicated column).

**Comment by joeljuca** [comment]
I figured out the problem wasn't with ExMachina, but with how I set up my Ecto schema. Sorry to bother!

Btw, for anyone who might be landing here in the future (eg: from search engines), I had to set up my Ecto migration and schema to proper understand my composite keys (btw it's called composite keys - not compound keys):

```ex
# the Ecto migration
def change do
  create table(:matches, primary_key: false) do
    add(:session_id, references(:sessions), null: false, primary_key: true)
    add(:user_id, references(:users), null: false, primary_key: true)

    timestamps()
  end
end

# the Ecto schema
schema "matches" do
  belongs_to(:session, Session, foreign_key: :session_id, primary_key: true)
  belongs_to(:user, User, foreign_key: :user_id, primary_key: true)

  timestamps()
end
```

The `primary_key: true` both in the migration and schema is important. Keep them in both places!

**Comment by germsvel** [comment]
Thanks for looping back and posting how you solved this. 👍
