### ISSUE TITLE
sequence(:example_id, & &1) put chars instead of integer

### ISSUE THREAD

**Issue by Liferenko** [thoughtbot/ex_machina#428]
There is a case when you're trying to make a list of digits. 
Add new item as `sequence(:blah_id, & &1)` and the list is 5-6-items-long.
The result in tests is not the list of digits but a string (list of chars) instead. 

Yep, it is predicted behaviour for Elixir/Erlang, but is there any solution to add a flag the same way it was added to `IO.inspect([0,1,2,3], charlist: :as_list)` to avoid digit-to-char conversion?

**Comment by halfdan** [comment]
There's no conversion happening. A list of digits that can be represented as a string just happens to be displayed as a string in iex. The list underneath is unchanged: 

```
iex(1)> a = [65, 66, 67]
'ABC'
iex(2)> hd(a)
65
```

**Comment by Liferenko** [comment]
well, that's exactly why I created this issue :) Theory said it appears only in IEx, but practice showed chars in my list from ExMachina.sequence/2

Here is an example:

**Comment by Liferenko** [comment]
Looks like it was my fault and I made this issue ticket due to my lack of experience. Sorry. Falce alarm
