### ISSUE TITLE
Clarify what the `attrs` parameter is and how it's used

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#51]
I just got done with a hangout with a few other Elixir/Phoenix users. One thing that was confusing to them was what the `attrs` are for. Since the example has them being used for assocs, it seems like that's all you could use them for. It is also unclear at what point the attrs are passed in, and *what* they are.

I think we should explain that the `attrs` are what you pass in as the second option to the build/create functions. Also maybe an example that uses attrs to build an email address from first and last name or something?

**Comment by henrik** [comment]
Should probably also explain that while it is what you pass as the second option, ExMachina will automagically merge the attributes, so this is why you can do `_attrs` if that's all you need. That confused me (and I'm not sure if I got it right).

**Comment by paulcsmith** [comment]
@henrik That's a great suggestion. I really appreciate your feedback. We definitely want to make sure the docs are as clear as possible!

**Comment by paulcsmith** [comment]
We've decided to remove the second parameter instead. See discussion in #56
