### ISSUE TITLE
Remove `attrs` as second parameter

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#56]
I've been thinking about this a lot. It seems `attrs` can be confusing and tricky to debug (see #54 and #51). I wonder if it would be better to remove it and instead handle associations after build. I imagine it would look something like this:

```elixir
def factory(:comment) do
  %Comment{
    body: "My Comment",
    author: belongs_to(:author)
  }
end

def belongs_to(key)  do
  %ExMachina.Ecto.BelongsTo{key: key}
end
```

Then in the build function it could iterate through the keys and if it comes along a `%ExMachina.Ecto.BelongsTo` struct it would build one. I think this makes factory definition and use a lot more clear, and clean. We'd lose the ability to use `attrs` inside the factory, but that causes bugs in a lot of cases anyway (https://github.com/thoughtbot/ex_machina/issues/54#issuecomment-155191465)

So I think it's better to leave the factory definitions as clean and clear as possible and do the transformation later

**Comment by paulcsmith** [comment]
Actually, I think we wouldn't even need a way to handle belongs_to. Now that we're building associations by default and only persisting them on create, I think we can just do 

```elixir
def factory(:comment) do
  %Comment{
    body: "My Comment",
    author: build(:author)
  }
end
```

So it builds a default, and it would be overridden if the user passes it in. I think this would remove some code and make things a lot simpler. Thoughts on this? @jsteiner

**Comment by jsteiner** [comment]
Yeah, that actually works out perfectly. I think we should move forward with this.

**Comment by henrik** [comment]
Can't speak to the implementation part, but from a user perspective this sounds great :thumbsup:

**Comment by paulcsmith** [comment]
Closed by https://github.com/thoughtbot/ex_machina/pull/57
