### ISSUE TITLE
Raise a helpful error letting people know to define factory/1 instead of factory/2

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#63]
We added an error here: https://github.com/thoughtbot/ex_machina/blob/0.5.0/lib/ex_machina.ex#L212

but that will never be called since internally we are calling factory/1. Instead that error message should be added to https://github.com/thoughtbot/ex_machina/blob/0.5.0/lib/ex_machina.ex#L16 `UndefinedFactory`. Something like:

```elixir
"""
No factory defined for #{inspect factory_name}. This may be because you have defined a factory with attrs like this: def factory(:my_factory, attrs)

This has been changed in 0.5.0 to just be: def factory(:my_factory). The assoc/2 function has also been removed. Please define your factory function like this:

def factory(#{inspect factory_name}) do
  ...
end
"""
```

**Comment by rranelli** [comment]
I think this issue can be closed, right?

**Comment by paulcsmith** [comment]
@rranelli Yes thank you for pointing that out. Slipped right by :)
