### ISSUE TITLE
Make a sequence/1 function that generates a default string

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#66]
A lot of times I just want a unique value like this:

```
title: sequence(:title, fn(n) -> "Title #{n}" end)
body: sequence(:comment_body, fn(n) -> "Comment Body #{n}" end)
```

For simple cases like this I think it would be helpful if you could do something like

```
title: sequence(:title) #generates "Title #{n}"
body: sequence(:comment_body) #generates "Comment Body #{n}"
```

Thoughts on this? Would it be better to use Faker or would this be useful?

**Comment by paulcsmith** [comment]
And maybe the name could be different. Like `gen_unique(:title)` or something like that

**Comment by jsteiner** [comment]
I really like `title: sequence(:title)`. Good idea!

I'd rather it be the same name (`sequence`) so it's easier to remember.

**Comment by paulcsmith** [comment]
Great! This is super easy to implement so I'll add that tomorrow :D

**Comment by paulcsmith** [comment]
Actually it might make sense to simplify this and make the first arg a string. So you would do:

```elixir
sequence("Title") # Generates "Title 1"
sequence("Comment Body") # Generate "Comment Body 1"
```

I think the key can be a binary so that might work better. Less indirection I think
