### ISSUE TITLE
`Create` fails for abstract / polymorphic tables

### ISSUE THREAD

**Issue by novaugust** [thoughtbot/ex_machina#81]
Using [polymorphic associations](https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3) and passing the `assoc_id` to `build/2` allows me to build records, but `create` fails as its trying to build with the abstract table name rather than the concrete one. The fun thing is, I can manually pipe whatever was built into a `Repo.insert!` and my insertion is successful.

```
# factory
  def factory(:vendor_image) do
    name = sequence(:filename, &"file-#{&1}.jpg")
    build_assoc(%Vendor{}, :images, [
      filename: name,
      alt: "Caption text for #{name}",
      medium: "priv/images/medium-#{name}",
      original: "priv/images/original-#{name}"
    ])
  end
# usage..
v = Factory.create(:vendor)

# fails, because its attempting to insert into the abstract table
i = Factory.create(:vendor_image, assoc_id: v.id)
# succeeds 
i = Factory.build(:vendor_image, assoc_id: v.id) |> Repo.insert!
```

**Comment by paulcsmith** [comment]
Thanks for submitting the issue.

I'll have to take a look at this next week. We may want to wait until Ecto 2.0 is finished because I think it will handle a lot of these edge cases automatically and it looks like it is coming along nicely. I'll post here with news.

**Comment by paulcsmith** [comment]
@novaugust This should be fixed in master. ExMachina now supports Ecto 2.0.0 (which is still in beta) and it should fix the issue you are having. If it doesn't please reopen the issue :D

**Comment by novaugust** [comment]
awesome, thanks for the ping. we've worked around it for now, so upgrading + reimplementing won't be at the top of our priorities for a bit, but i'll definitely hit you back when we do it
(cc @jthopple)
