### ISSUE TITLE
Add functions for `insert` `insert_pair` `insert_list` in ExMachina.Ecto

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#89]
These would just delegate to the `create` versions. I think this maps better to the Ecto terminology of inserting records.

`insert(:user)`
`insert_pair(:user)`
`insert_list(:user)`

Thoughts?

**Comment by paulcsmith** [comment]
@jsteiner @BlakeWilliams Any thoughts on this? I think this pairs with Ecto better than the create functions, what do you think?

**Comment by BlakeWilliams** [comment]
:+1: from me. I'm a fan of keeping it consistent.
