### ISSUE TITLE
Raise helpful error if you accidentally call insert twice

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#90]
I accidentally did this:

```elixir
appointment_booking = create(:appointment_booking)
  |> set_appointment_price(500)
  |> insert
```

And got this error:

```
* (Ecto.ConstraintError) constraint error when attempting to insert model:

         * unique: appointment_booking_pkey

     If you would like to convert this constraint into an error, please
     call unique_constraint/3 in your changeset and define the proper
     constraint name. The changeset has not defined any constraint.
```

I think it would be helpful if it said something like:

```
you called `insert` on #{the record} but it was already saved. You can only call insert on records that haven't been inserted yet
```

Or something along those lines. This is pretty low priority, but might be nice to have

**Comment by geofflane** [comment]
This might happen  with related models as well. I think I've seen something like the following.

```
build(:user)
|> with_role(:admin)
|> create
```

Where `with roles` is defined like:
```
def with_roles(user, role) do
  %{user | roles: [create(:role, name: role)]}
end
```

It sees the association and tries to re-save it. I think the error message like you said would have helped a lot in that situation as well.

**Comment by paulcsmith** [comment]
Thanks for the feedback. I'm glad to hear this would have helped. I'll try to get this in to 1.0 :)

Or if you want to try tackling it, that would be cool as well! Happy to help if you're interested in taking it on

**Comment by davidkuhta** [comment]
@paulcsmith - This is a separate branch from the "error-helpers" one in #106 
Gave this a try based on evaluating the metadata before handling the `insert` and checking if the state is `:loaded` vs `:built` per [Ecto.Schema.Metadata Hexdocs](https://hexdocs.pm/ecto/2.0.0-beta.2/Ecto.Schema.Metadata.html.)
So:
```
  def handle_insert(%{__meta__: %{__struct__: Ecto.Schema.Metadata} = metadata} = record, %{repo: repo}) do
    case metadata.state do
      :loaded ->
        raise ArgumentError,
        "you called `insert` on #{inspect record} but it has already been saved.
         You can only call `insert` on records that haven't been inserted yet"
      :built ->
        repo.insert! record
    end
  end
```


[Relevant Code](https://github.com/davidkuhta/ex_machina/blob/insert-twice/lib/ex_machina/ecto_strategy.ex#L6)
https://github.com/davidkuhta/ex_machina/blob/insert-twice/lib/ex_machina/ecto_strategy.ex#L6

[Double Insert Test](https://github.com/davidkuhta/ex_machina/blob/insert-twice/test/ex_machina/ecto_strategy_test.exs#L83)

**Comment by paulcsmith** [comment]
@davidkuhta Could you open a PR for this one as well? After a quick look I think we could do two different functions and match on it, or simplify the conditional. Here's what I'm thinking

```elixir
def handle_insert(%{__meta__: %{state: :loaded}} = record) do
  raise "..."
end

def handle_insert(record) do
  repo.insert!(record)
end
```
