### ISSUE TITLE
Change `fields_for` to `params_for`

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#96]
I often use `fields_for` when creating or updating records in API endpoints or for testing controllers. I think `params_for` makes more sense in these cases.

`post comment_path(conn, :create), params_for(:comment)`

**Comment by BlakeWilliams** [comment]
I personally like `fields_for` because of what the function does but I don't feel strongly about it. LGTM

**Comment by paulcsmith** [comment]
Closed by #98
