### ISSUE TITLE
Implement a factory linting method like in FactoryGirl

### ISSUE THREAD

**Issue by lpil** [thoughtbot/ex_machina#97]
I've found this useful for asserting the validity of my factories when working in Ruby, and think it would be nice in Elixir too. :)

https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#linting-factories

**Comment by paulcsmith** [comment]
@lpil I'm not entirely sure how this would work since the factory module is a bunch of functions with the same arity, so I don't know of a way to get a list of the defined factories. I'll have to look into this more.

Thanks for the suggestion

**Comment by paulcsmith** [comment]
In that case I think you could just create a test in `test/factory_test.exs`

```elixir
defmodule MyApp.FactoryTest do
  use ExUnit.Case

  test "all factories can save correctly" do
    for factory <- ~w(user project task whatever) do
      MyApp.Factory.create(factory)
    end
  end
end
```

Would that solve what you're trying to do? And if you wanted to add a task instead, you could do the same thing but in a task module that you run inside `test_helper.exs`

```elixir
defmodule Mix.Tasks.MyApp.LintFactories do
  use Mix.Task

  def run(_opts) do
    Mix.Task.run "app.start"

    for factory <- ~w(user project task whatever) do
      MyApp.Factory.create(factory)
    end
  end
end

# test_helper.exs
Mix.Task.run "lint_factories"
```

**Comment by lpil** [comment]
Basically this but with helpful error messages and such so everyone doesn't have to rebuild this. Additionally if this exists it will encourage people to lint their factories and possibly write better code as a result.

**Comment by paulcsmith** [comment]
@lpil What kind of error message do you think would be helpful? I personally don't think I'd use linting like this since when I run the test suite and there's with a factory I will see the error. If that error is from Ecto it's usually pretty clear (usually a null constraint). So before I add something like this, could you provide an example of when something has gone wrong, and an error that you think would have helped you solve the problem? That would help us figure out a solution

**Comment by paulcsmith** [comment]
@lpil I'm going to close this for now. Right now I'm not sure I understand the benefit. Please comment here if you could give an example of what kind of helpful error messages you think would be helpful though! :+1:

**Comment by lpil** [comment]
Hey Paul

With my Dogma project I've done quite a bit of reflection on Elixir module's AST, and now that I think it would be relativelt easy to get the names of all the factories this way. Would you be interested in a pull request doing this?

Cheers,
Louis

**Comment by paulcsmith** [comment]
@lpil I'd definitely be open to it! I would hold off for a bit though. I think I'll be changing the factory definition soon #101 which would affect how you would find defined factories.

Also before starting, could you outline roughly what you want the tool to do and how it would be used? I wouldn't want you to go to all the work of writing the code if we're not sure how it will look or if we'll accept it

**Comment by lpil** [comment]
Certainly. I'll wait until after the other ticket is closed.

**Comment by paulcsmith** [comment]
Perfect! :+1:

**Comment by paulcsmith** [comment]
@lpil The changes to factory definition are now in. I think I'd like to keep linting in a separate project for now. What do you think about making ex_machina_lint (or whatever name you prefer)? I would be happy to link to it in the README for those that want to use it. If there is a lot of interest we could talk about adding it to core later. What do you think?

**Comment by lpil** [comment]
Sounds reasonable :)

**Comment by paulcsmith** [comment]
Great! Feel free to ping me or open an issue/PR when you're ready for it to be added to the README :)

**Comment by lpil** [comment]
May be hard to do without adding an accumulator to the mechanism used for defining factories. I'll have a look.

**Comment by paulcsmith** [comment]
I imagine that you could iterate over the functions and get all the functions with 0 arity that end with `_factory`. Might not be 100% reliable, but maybe it would work?

**Comment by lpil** [comment]
Oh, that's a good idea. Thank you. :)
